// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// tl_main package generated by `tlgen.py` tool

package tl_main_pkg;

  localparam logic [0:0][31:0] ADDR_SPACE_PERI                = {
    32'h 30000000
  };
  localparam logic [31:0] ADDR_SPACE_SOC_PROXY__CTN      = 32'h 40000000;
  localparam logic [31:0] ADDR_SPACE_HMAC                = 32'h 21110000;
  localparam logic [31:0] ADDR_SPACE_KMAC                = 32'h 21120000;
  localparam logic [31:0] ADDR_SPACE_AES                 = 32'h 21100000;
  localparam logic [31:0] ADDR_SPACE_OTBN                = 32'h 21130000;
  localparam logic [31:0] ADDR_SPACE_KEYMGR_DPE          = 32'h 21140000;
  localparam logic [31:0] ADDR_SPACE_SRAM_CTRL_MAIN__RAM = 32'h 10000000;
  localparam logic [31:0] ADDR_SPACE_SRAM_CTRL_MBOX__RAM = 32'h 11000000;

  localparam logic [0:0][31:0] ADDR_MASK_PERI                = {
    32'h 007fffff
  };
  localparam logic [31:0] ADDR_MASK_SOC_PROXY__CTN      = 32'h 3fffffff;
  localparam logic [31:0] ADDR_MASK_HMAC                = 32'h 00001fff;
  localparam logic [31:0] ADDR_MASK_KMAC                = 32'h 00000fff;
  localparam logic [31:0] ADDR_MASK_AES                 = 32'h 000000ff;
  localparam logic [31:0] ADDR_MASK_OTBN                = 32'h 0000ffff;
  localparam logic [31:0] ADDR_MASK_KEYMGR_DPE          = 32'h 000000ff;
  localparam logic [31:0] ADDR_MASK_SRAM_CTRL_MAIN__RAM = 32'h 0000ffff;
  localparam logic [31:0] ADDR_MASK_SRAM_CTRL_MBOX__RAM = 32'h 00000fff;

  localparam int N_HOST   = 11;
  localparam int N_DEVICE = 9;

  typedef enum int {
    TlPeri = 0,
    TlSocProxyCtn = 1,
    TlHmac = 2,
    TlKmac = 3,
    TlAes = 4,
    TlOtbn = 5,
    TlKeymgrDpe = 6,
    TlSramCtrlMainRam = 7,
    TlSramCtrlMboxRam = 8
  } tl_device_e;

  typedef enum int {
    TlDmaHost = 0,
    TlMbx0Sram = 1,
    TlMbx1Sram = 2,
    TlMbx2Sram = 3,
    TlMbx3Sram = 4,
    TlMbx4Sram = 5,
    TlMbx5Sram = 6,
    TlMbx6Sram = 7,
    TlMbxJtagSram = 8,
    TlMbxPcie0Sram = 9,
    TlMbxPcie1Sram = 10
  } tl_host_e;

endpackage
