// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// xbar_env_pkg__params generated by `tlgen.py` tool


// List of Xbar device memory map
tl_device_t xbar_devices[$] = '{
    '{"uart0", '{
        '{32'h30010000, 32'h3001003f}
    }},
    '{"gpio", '{
        '{32'h30000000, 32'h300000ff}
    }},
    '{"rv_timer", '{
        '{32'h30100000, 32'h301001ff}
    }},
    '{"pwrmgr_aon", '{
        '{32'h30400000, 32'h3040007f}
    }},
    '{"rstmgr_aon", '{
        '{32'h30410000, 32'h3041003f}
    }},
    '{"clkmgr_aon", '{
        '{32'h30420000, 32'h3042003f}
    }},
    '{"pinmux_aon", '{
        '{32'h30460000, 32'h304607ff}
    }},
    '{"otp_ctrl__core", '{
        '{32'h30130000, 32'h30137fff}
    }},
    '{"lc_ctrl__regs", '{
        '{32'h30150000, 32'h301500ff}
    }},
    '{"alert_handler", '{
        '{32'h30160000, 32'h301607ff}
    }},
    '{"sram_ctrl_ret_aon__regs", '{
        '{32'h30500000, 32'h3050003f}
    }},
    '{"sram_ctrl_ret_aon__ram", '{
        '{32'h30600000, 32'h30600fff}
    }},
    '{"aon_timer_aon", '{
        '{32'h30470000, 32'h3047003f}
    }},
    '{"soc_dbg_ctrl__core", '{
        '{32'h30170000, 32'h3017001f}
}}};

  // List of Xbar hosts
tl_host_t xbar_hosts[$] = '{
    '{"main", 0, '{
        "uart0",
        "gpio",
        "rv_timer",
        "pwrmgr_aon",
        "rstmgr_aon",
        "clkmgr_aon",
        "pinmux_aon",
        "otp_ctrl__core",
        "lc_ctrl__regs",
        "alert_handler",
        "sram_ctrl_ret_aon__ram",
        "sram_ctrl_ret_aon__regs",
        "aon_timer_aon",
        "soc_dbg_ctrl__core"}}
};
