// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// xbar_env_pkg__params generated by `tlgen.py` tool


// List of Xbar device memory map
tl_device_t xbar_devices[$] = '{
    '{"peri", '{
        '{32'h30000000, 32'h307fffff}
    }},
    '{"soc_proxy__ctn", '{
        '{32'h40000000, 32'h7fffffff}
    }},
    '{"hmac", '{
        '{32'h21110000, 32'h21111fff}
    }},
    '{"kmac", '{
        '{32'h21120000, 32'h21120fff}
    }},
    '{"aes", '{
        '{32'h21100000, 32'h211000ff}
    }},
    '{"otbn", '{
        '{32'h21130000, 32'h2113ffff}
    }},
    '{"keymgr_dpe", '{
        '{32'h21140000, 32'h211400ff}
    }},
    '{"sram_ctrl_main__ram", '{
        '{32'h10000000, 32'h1000ffff}
    }},
    '{"sram_ctrl_mbox__ram", '{
        '{32'h11000000, 32'h11000fff}
}}};

  // List of Xbar hosts
tl_host_t xbar_hosts[$] = '{
    '{"dma__host", 0, '{
        "sram_ctrl_main__ram",
        "sram_ctrl_mbox__ram",
        "aes",
        "hmac",
        "otbn",
        "keymgr_dpe",
        "kmac",
        "soc_proxy__ctn",
        "peri"}}
    ,
    '{"mbx0__sram", 1, '{
        "sram_ctrl_mbox__ram"}}
    ,
    '{"mbx1__sram", 2, '{
        "sram_ctrl_mbox__ram"}}
    ,
    '{"mbx2__sram", 3, '{
        "sram_ctrl_mbox__ram"}}
    ,
    '{"mbx3__sram", 4, '{
        "sram_ctrl_mbox__ram"}}
    ,
    '{"mbx4__sram", 5, '{
        "sram_ctrl_mbox__ram"}}
    ,
    '{"mbx5__sram", 6, '{
        "sram_ctrl_mbox__ram"}}
    ,
    '{"mbx6__sram", 7, '{
        "sram_ctrl_mbox__ram"}}
    ,
    '{"mbx_jtag__sram", 8, '{
        "sram_ctrl_mbox__ram"}}
    ,
    '{"mbx_pcie0__sram", 9, '{
        "sram_ctrl_mbox__ram"}}
    ,
    '{"mbx_pcie1__sram", 10, '{
        "sram_ctrl_mbox__ram"}}
};
