// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// xbar_env_pkg__params generated by `topgen.py` tool


// List of Xbar device memory map
tl_device_t xbar_devices[$] = '{
    '{"soc_proxy__ctn", '{
        '{32'h40000000, 32'h7fffffff}
    }},
    '{"hmac", '{
        '{32'h21110000, 32'h21111fff}
    }},
    '{"kmac", '{
        '{32'h21120000, 32'h21120fff}
    }},
    '{"aes", '{
        '{32'h21100000, 32'h211000ff}
    }},
    '{"otbn", '{
        '{32'h21130000, 32'h2113ffff}
    }},
    '{"keymgr_dpe", '{
        '{32'h21140000, 32'h211400ff}
    }},
    '{"sram_ctrl_main__ram", '{
        '{32'h10000000, 32'h1000ffff}
    }},
    '{"sram_ctrl_mbox__ram", '{
        '{32'h11000000, 32'h11000fff}
    }},
    '{"uart0", '{
        '{32'h30010000, 32'h3001003f}
    }},
    '{"i2c0", '{
        '{32'h30080000, 32'h3008007f}
    }},
    '{"gpio", '{
        '{32'h30000000, 32'h300000ff}
    }},
    '{"spi_host0", '{
        '{32'h30300000, 32'h3030003f}
    }},
    '{"spi_device", '{
        '{32'h30310000, 32'h30311fff}
    }},
    '{"pwrmgr_aon", '{
        '{32'h30400000, 32'h3040007f}
    }},
    '{"rstmgr_aon", '{
        '{32'h30410000, 32'h3041007f}
    }},
    '{"clkmgr_aon", '{
        '{32'h30420000, 32'h3042003f}
    }},
    '{"pinmux_aon", '{
        '{32'h30460000, 32'h304607ff}
    }},
    '{"otp_ctrl__core", '{
        '{32'h30130000, 32'h30137fff}
    }},
    '{"otp_macro__prim", '{
        '{32'h30140000, 32'h3014001f}
    }},
    '{"lc_ctrl__regs", '{
        '{32'h30150000, 32'h301500ff}
    }},
    '{"alert_handler", '{
        '{32'h30160000, 32'h301607ff}
    }},
    '{"sram_ctrl_ret_aon__regs", '{
        '{32'h30500000, 32'h3050003f}
    }},
    '{"sram_ctrl_ret_aon__ram", '{
        '{32'h30600000, 32'h30600fff}
    }},
    '{"aon_timer_aon", '{
        '{32'h30470000, 32'h3047003f}
    }},
    '{"ast", '{
        '{32'h30480000, 32'h304803ff}
    }},
    '{"soc_dbg_ctrl__core", '{
        '{32'h30170000, 32'h3017001f}
    }},
    '{"mbx0__soc", '{
        '{32'h01465000, 32'h0146501f}
    }},
    '{"mbx1__soc", '{
        '{32'h01465100, 32'h0146511f}
    }},
    '{"mbx2__soc", '{
        '{32'h01465200, 32'h0146521f}
    }},
    '{"mbx3__soc", '{
        '{32'h01465300, 32'h0146531f}
    }},
    '{"mbx4__soc", '{
        '{32'h01465400, 32'h0146541f}
    }},
    '{"mbx5__soc", '{
        '{32'h01465500, 32'h0146551f}
    }},
    '{"mbx6__soc", '{
        '{32'h01496000, 32'h0149601f}
    }},
    '{"mbx_pcie0__soc", '{
        '{32'h01460100, 32'h0146011f}
    }},
    '{"mbx_pcie1__soc", '{
        '{32'h01460200, 32'h0146021f}
    }},
    '{"racl_ctrl", '{
        '{32'h01461f00, 32'h01461fff}
    }},
    '{"ac_range_check", '{
        '{32'h01464000, 32'h014643ff}
    }},
    '{"mbx_jtag__soc", '{
        '{32'h00002200, 32'h0000221f}
    }},
    '{"lc_ctrl__dmi", '{
        '{32'h00003000, 32'h00003fff}
    }},
    '{"soc_dbg_ctrl__jtag", '{
        '{32'h00002300, 32'h0000231f}
    }}};

  // List of Xbar hosts
tl_host_t xbar_hosts[$] = '{
    '{"dma__host", 0, '{
        "sram_ctrl_main__ram",
        "sram_ctrl_mbox__ram",
        "aes",
        "hmac",
        "otbn",
        "keymgr_dpe",
        "kmac",
        "soc_proxy__ctn",
        "uart0",
        "i2c0",
        "gpio",
        "spi_host0",
        "spi_device",
        "pwrmgr_aon",
        "rstmgr_aon",
        "clkmgr_aon",
        "pinmux_aon",
        "otp_ctrl__core",
        "otp_macro__prim",
        "lc_ctrl__regs",
        "alert_handler",
        "ast",
        "sram_ctrl_ret_aon__ram",
        "sram_ctrl_ret_aon__regs",
        "aon_timer_aon",
        "soc_dbg_ctrl__core"}}
    ,
    '{"mbx0__sram", 1, '{
        "sram_ctrl_mbox__ram"}}
    ,
    '{"mbx1__sram", 2, '{
        "sram_ctrl_mbox__ram"}}
    ,
    '{"mbx2__sram", 3, '{
        "sram_ctrl_mbox__ram"}}
    ,
    '{"mbx3__sram", 4, '{
        "sram_ctrl_mbox__ram"}}
    ,
    '{"mbx4__sram", 5, '{
        "sram_ctrl_mbox__ram"}}
    ,
    '{"mbx5__sram", 6, '{
        "sram_ctrl_mbox__ram"}}
    ,
    '{"mbx6__sram", 7, '{
        "sram_ctrl_mbox__ram"}}
    ,
    '{"mbx_jtag__sram", 8, '{
        "sram_ctrl_mbox__ram"}}
    ,
    '{"mbx_pcie0__sram", 9, '{
        "sram_ctrl_mbox__ram"}}
    ,
    '{"mbx_pcie1__sram", 10, '{
        "sram_ctrl_mbox__ram"}}
};
