// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package acc_reg_pkg;

  // Param list
  parameter int NumAlerts = 2;

  // Address widths within the block
  parameter int BlockAw = 17;

  // Number of registers for every interface
  parameter int NumRegs = 11;

  // Alert indices
  typedef enum int {
    AlertFatalIdx = 0,
    AlertRecovIdx = 1
  } acc_alert_idx_t;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {
    logic        q;
  } acc_reg2hw_intr_state_reg_t;

  typedef struct packed {
    logic        q;
  } acc_reg2hw_intr_enable_reg_t;

  typedef struct packed {
    logic        q;
    logic        qe;
  } acc_reg2hw_intr_test_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
      logic        qe;
    } recov;
    struct packed {
      logic        q;
      logic        qe;
    } fatal;
  } acc_reg2hw_alert_test_reg_t;

  typedef struct packed {
    logic [7:0]  q;
    logic        qe;
  } acc_reg2hw_cmd_reg_t;

  typedef struct packed {
    logic        q;
    logic        qe;
  } acc_reg2hw_ctrl_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
      logic        qe;
    } fatal_software;
    struct packed {
      logic        q;
      logic        qe;
    } lifecycle_escalation;
    struct packed {
      logic        q;
      logic        qe;
    } illegal_bus_access;
    struct packed {
      logic        q;
      logic        qe;
    } bad_internal_state;
    struct packed {
      logic        q;
      logic        qe;
    } bus_intg_violation;
    struct packed {
      logic        q;
      logic        qe;
    } reg_intg_violation;
    struct packed {
      logic        q;
      logic        qe;
    } dmem_intg_violation;
    struct packed {
      logic        q;
      logic        qe;
    } imem_intg_violation;
    struct packed {
      logic        q;
      logic        qe;
    } rnd_fips_chk_fail;
    struct packed {
      logic        q;
      logic        qe;
    } rnd_rep_chk_fail;
    struct packed {
      logic        q;
      logic        qe;
    } key_invalid;
    struct packed {
      logic        q;
      logic        qe;
    } loop;
    struct packed {
      logic        q;
      logic        qe;
    } illegal_insn;
    struct packed {
      logic        q;
      logic        qe;
    } call_stack;
    struct packed {
      logic        q;
      logic        qe;
    } bad_insn_addr;
    struct packed {
      logic        q;
      logic        qe;
    } bad_data_addr;
  } acc_reg2hw_err_bits_reg_t;

  typedef struct packed {
    logic [31:0] q;
    logic        qe;
  } acc_reg2hw_insn_cnt_reg_t;

  typedef struct packed {
    logic [31:0] q;
    logic        qe;
  } acc_reg2hw_load_checksum_reg_t;

  typedef struct packed {
    logic        d;
    logic        de;
  } acc_hw2reg_intr_state_reg_t;

  typedef struct packed {
    logic        d;
  } acc_hw2reg_ctrl_reg_t;

  typedef struct packed {
    logic [7:0]  d;
    logic        de;
  } acc_hw2reg_status_reg_t;

  typedef struct packed {
    struct packed {
      logic        d;
    } fatal_software;
    struct packed {
      logic        d;
    } lifecycle_escalation;
    struct packed {
      logic        d;
    } illegal_bus_access;
    struct packed {
      logic        d;
    } bad_internal_state;
    struct packed {
      logic        d;
    } bus_intg_violation;
    struct packed {
      logic        d;
    } reg_intg_violation;
    struct packed {
      logic        d;
    } dmem_intg_violation;
    struct packed {
      logic        d;
    } imem_intg_violation;
    struct packed {
      logic        d;
    } rnd_fips_chk_fail;
    struct packed {
      logic        d;
    } rnd_rep_chk_fail;
    struct packed {
      logic        d;
    } key_invalid;
    struct packed {
      logic        d;
    } loop;
    struct packed {
      logic        d;
    } illegal_insn;
    struct packed {
      logic        d;
    } call_stack;
    struct packed {
      logic        d;
    } bad_insn_addr;
    struct packed {
      logic        d;
    } bad_data_addr;
  } acc_hw2reg_err_bits_reg_t;

  typedef struct packed {
    struct packed {
      logic        d;
      logic        de;
    } fatal_software;
    struct packed {
      logic        d;
      logic        de;
    } lifecycle_escalation;
    struct packed {
      logic        d;
      logic        de;
    } illegal_bus_access;
    struct packed {
      logic        d;
      logic        de;
    } bad_internal_state;
    struct packed {
      logic        d;
      logic        de;
    } bus_intg_violation;
    struct packed {
      logic        d;
      logic        de;
    } reg_intg_violation;
    struct packed {
      logic        d;
      logic        de;
    } dmem_intg_violation;
    struct packed {
      logic        d;
      logic        de;
    } imem_intg_violation;
  } acc_hw2reg_fatal_alert_cause_reg_t;

  typedef struct packed {
    logic [31:0] d;
  } acc_hw2reg_insn_cnt_reg_t;

  typedef struct packed {
    logic [31:0] d;
  } acc_hw2reg_load_checksum_reg_t;

  // Register -> HW type
  typedef struct packed {
    acc_reg2hw_intr_state_reg_t intr_state; // [116:116]
    acc_reg2hw_intr_enable_reg_t intr_enable; // [115:115]
    acc_reg2hw_intr_test_reg_t intr_test; // [114:113]
    acc_reg2hw_alert_test_reg_t alert_test; // [112:109]
    acc_reg2hw_cmd_reg_t cmd; // [108:100]
    acc_reg2hw_ctrl_reg_t ctrl; // [99:98]
    acc_reg2hw_err_bits_reg_t err_bits; // [97:66]
    acc_reg2hw_insn_cnt_reg_t insn_cnt; // [65:33]
    acc_reg2hw_load_checksum_reg_t load_checksum; // [32:0]
  } acc_reg2hw_t;

  // HW -> register type
  typedef struct packed {
    acc_hw2reg_intr_state_reg_t intr_state; // [107:106]
    acc_hw2reg_ctrl_reg_t ctrl; // [105:105]
    acc_hw2reg_status_reg_t status; // [104:96]
    acc_hw2reg_err_bits_reg_t err_bits; // [95:80]
    acc_hw2reg_fatal_alert_cause_reg_t fatal_alert_cause; // [79:64]
    acc_hw2reg_insn_cnt_reg_t insn_cnt; // [63:32]
    acc_hw2reg_load_checksum_reg_t load_checksum; // [31:0]
  } acc_hw2reg_t;

  // Register offsets
  parameter logic [BlockAw-1:0] ACC_INTR_STATE_OFFSET = 17'h 0;
  parameter logic [BlockAw-1:0] ACC_INTR_ENABLE_OFFSET = 17'h 4;
  parameter logic [BlockAw-1:0] ACC_INTR_TEST_OFFSET = 17'h 8;
  parameter logic [BlockAw-1:0] ACC_ALERT_TEST_OFFSET = 17'h c;
  parameter logic [BlockAw-1:0] ACC_CMD_OFFSET = 17'h 10;
  parameter logic [BlockAw-1:0] ACC_CTRL_OFFSET = 17'h 14;
  parameter logic [BlockAw-1:0] ACC_STATUS_OFFSET = 17'h 18;
  parameter logic [BlockAw-1:0] ACC_ERR_BITS_OFFSET = 17'h 1c;
  parameter logic [BlockAw-1:0] ACC_FATAL_ALERT_CAUSE_OFFSET = 17'h 20;
  parameter logic [BlockAw-1:0] ACC_INSN_CNT_OFFSET = 17'h 24;
  parameter logic [BlockAw-1:0] ACC_LOAD_CHECKSUM_OFFSET = 17'h 28;

  // Reset values for hwext registers and their fields
  parameter logic [0:0] ACC_INTR_TEST_RESVAL = 1'h 0;
  parameter logic [0:0] ACC_INTR_TEST_DONE_RESVAL = 1'h 0;
  parameter logic [1:0] ACC_ALERT_TEST_RESVAL = 2'h 0;
  parameter logic [0:0] ACC_ALERT_TEST_FATAL_RESVAL = 1'h 0;
  parameter logic [0:0] ACC_ALERT_TEST_RECOV_RESVAL = 1'h 0;
  parameter logic [7:0] ACC_CMD_RESVAL = 8'h 0;
  parameter logic [7:0] ACC_CMD_CMD_RESVAL = 8'h 0;
  parameter logic [0:0] ACC_CTRL_RESVAL = 1'h 0;
  parameter logic [0:0] ACC_CTRL_SOFTWARE_ERRS_FATAL_RESVAL = 1'h 0;
  parameter logic [23:0] ACC_ERR_BITS_RESVAL = 24'h 0;
  parameter logic [0:0] ACC_ERR_BITS_BAD_DATA_ADDR_RESVAL = 1'h 0;
  parameter logic [0:0] ACC_ERR_BITS_BAD_INSN_ADDR_RESVAL = 1'h 0;
  parameter logic [0:0] ACC_ERR_BITS_CALL_STACK_RESVAL = 1'h 0;
  parameter logic [0:0] ACC_ERR_BITS_ILLEGAL_INSN_RESVAL = 1'h 0;
  parameter logic [0:0] ACC_ERR_BITS_LOOP_RESVAL = 1'h 0;
  parameter logic [0:0] ACC_ERR_BITS_KEY_INVALID_RESVAL = 1'h 0;
  parameter logic [0:0] ACC_ERR_BITS_RND_REP_CHK_FAIL_RESVAL = 1'h 0;
  parameter logic [0:0] ACC_ERR_BITS_RND_FIPS_CHK_FAIL_RESVAL = 1'h 0;
  parameter logic [0:0] ACC_ERR_BITS_IMEM_INTG_VIOLATION_RESVAL = 1'h 0;
  parameter logic [0:0] ACC_ERR_BITS_DMEM_INTG_VIOLATION_RESVAL = 1'h 0;
  parameter logic [0:0] ACC_ERR_BITS_REG_INTG_VIOLATION_RESVAL = 1'h 0;
  parameter logic [0:0] ACC_ERR_BITS_BUS_INTG_VIOLATION_RESVAL = 1'h 0;
  parameter logic [0:0] ACC_ERR_BITS_BAD_INTERNAL_STATE_RESVAL = 1'h 0;
  parameter logic [0:0] ACC_ERR_BITS_ILLEGAL_BUS_ACCESS_RESVAL = 1'h 0;
  parameter logic [0:0] ACC_ERR_BITS_LIFECYCLE_ESCALATION_RESVAL = 1'h 0;
  parameter logic [0:0] ACC_ERR_BITS_FATAL_SOFTWARE_RESVAL = 1'h 0;
  parameter logic [31:0] ACC_INSN_CNT_RESVAL = 32'h 0;
  parameter logic [31:0] ACC_INSN_CNT_INSN_CNT_RESVAL = 32'h 0;
  parameter logic [31:0] ACC_LOAD_CHECKSUM_RESVAL = 32'h 0;
  parameter logic [31:0] ACC_LOAD_CHECKSUM_CHECKSUM_RESVAL = 32'h 0;

  // Window parameters
  parameter logic [BlockAw-1:0] ACC_IMEM_OFFSET = 17'h 8000;
  parameter int unsigned        ACC_IMEM_SIZE   = 'h 8000;
  parameter int unsigned        ACC_IMEM_IDX    = 0;
  parameter logic [BlockAw-1:0] ACC_DMEM_OFFSET = 17'h 18000;
  parameter int unsigned        ACC_DMEM_SIZE   = 'h 7c00;
  parameter int unsigned        ACC_DMEM_IDX    = 1;

  // Register index
  typedef enum int {
    ACC_INTR_STATE,
    ACC_INTR_ENABLE,
    ACC_INTR_TEST,
    ACC_ALERT_TEST,
    ACC_CMD,
    ACC_CTRL,
    ACC_STATUS,
    ACC_ERR_BITS,
    ACC_FATAL_ALERT_CAUSE,
    ACC_INSN_CNT,
    ACC_LOAD_CHECKSUM
  } acc_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] ACC_PERMIT [11] = '{
    4'b 0001, // index[ 0] ACC_INTR_STATE
    4'b 0001, // index[ 1] ACC_INTR_ENABLE
    4'b 0001, // index[ 2] ACC_INTR_TEST
    4'b 0001, // index[ 3] ACC_ALERT_TEST
    4'b 0001, // index[ 4] ACC_CMD
    4'b 0001, // index[ 5] ACC_CTRL
    4'b 0001, // index[ 6] ACC_STATUS
    4'b 0111, // index[ 7] ACC_ERR_BITS
    4'b 0001, // index[ 8] ACC_FATAL_ALERT_CAUSE
    4'b 1111, // index[ 9] ACC_INSN_CNT
    4'b 1111  // index[10] ACC_LOAD_CHECKSUM
  };

endpackage
