# Copyright lowRISC contributors (OpenTitan project).
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "fi_rng",
    srcs = ["fi_rng.json"],
)

filegroup(
    name = "fi_ibex",
    srcs = ["fi_ibex.json"],
)

filegroup(
    name = "fi_acc",
    srcs = ["fi_acc.json"],
)

filegroup(
    name = "fi_otp",
    srcs = ["fi_otp.json"],
)

filegroup(
    name = "fi_rom",
    srcs = ["fi_rom.json"],
)

filegroup(
    name = "fi_crypto",
    srcs = ["fi_crypto.json"],
)
