# Copyright lowRISC contributors (OpenTitan project).
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

load("//rules:acc.bzl", "acc_binary")

package(default_visibility = ["//visibility:public"])

acc_binary(
    name = "acc_char_beq",
    srcs = [
        "acc_char_beq.s",
    ],
)

acc_binary(
    name = "acc_char_bn_rshi",
    srcs = [
        "acc_char_bn_rshi.s",
    ],
)

acc_binary(
    name = "acc_char_bn_sel",
    srcs = [
        "acc_char_bn_sel.s",
    ],
)

acc_binary(
    name = "acc_char_bn_wsrr",
    srcs = [
        "acc_char_bn_wsrr.s",
    ],
)

acc_binary(
    name = "acc_char_bne",
    srcs = [
        "acc_char_bne.s",
    ],
)

acc_binary(
    name = "acc_char_dmem_access",
    srcs = [
        "acc_char_dmem_access.s",
    ],
)

acc_binary(
    name = "acc_char_dmem_write",
    srcs = [
        "acc_char_dmem_write.s",
    ],
)

acc_binary(
    name = "acc_char_hardware_dmem_op_loop",
    srcs = [
        "acc_char_hardware_dmem_op_loop.s",
    ],
)

acc_binary(
    name = "acc_char_hardware_reg_op_loop",
    srcs = [
        "acc_char_hardware_reg_op_loop.s",
    ],
)

acc_binary(
    name = "acc_char_jal",
    srcs = [
        "acc_char_jal.s",
    ],
)

acc_binary(
    name = "acc_char_lw",
    srcs = [
        "acc_char_lw.s",
    ],
)

acc_binary(
    name = "acc_char_rf",
    srcs = [
        "acc_char_rf.s",
    ],
)

acc_binary(
    name = "acc_char_unrolled_dmem_op_loop",
    srcs = [
        "acc_char_unrolled_dmem_op_loop.s",
    ],
)

acc_binary(
    name = "acc_char_unrolled_reg_op_loop",
    srcs = [
        "acc_char_unrolled_reg_op_loop.s",
    ],
)

acc_binary(
    name = "acc_key_sideload",
    srcs = [
        "acc_key_sideload.s",
    ],
)

acc_binary(
    name = "acc_load_integrity",
    srcs = [
        "acc_load_integrity.s",
    ],
)

acc_binary(
    name = "acc_pc",
    srcs = [
        "acc_pc.s",
    ],
)
