// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// ------------------- W A R N I N G: A U T O - G E N E R A T E D   C O D E !! -------------------//
// PLEASE DO NOT HAND-EDIT THIS FILE. IT HAS BEEN AUTO-GENERATED WITH THE FOLLOWING COMMAND:
// util/topgen.py -t hw/top_daric2/data/top_daric2.hjson
// -o hw/top_daric2

#include "hw/top_daric2/sw/autogen/top_daric2.h"

/**
 * Alert Handler Alert Source to Peripheral Map
 *
 * This array is a mapping from `top_daric2_alert_id_t` to
 * `top_daric2_alert_peripheral_t`.
 */
const top_daric2_alert_peripheral_t
    top_daric2_alert_for_peripheral[96] = {
  [kTopDaric2AlertIdUart0FatalFault] = kTopDaric2AlertPeripheralUart0,
  [kTopDaric2AlertIdGpioFatalFault] = kTopDaric2AlertPeripheralGpio,
  [kTopDaric2AlertIdRvTimerFatalFault] = kTopDaric2AlertPeripheralRvTimer,
  [kTopDaric2AlertIdOtpCtrlFatalMacroError] = kTopDaric2AlertPeripheralOtpCtrl,
  [kTopDaric2AlertIdOtpCtrlFatalCheckError] = kTopDaric2AlertPeripheralOtpCtrl,
  [kTopDaric2AlertIdOtpCtrlFatalBusIntegError] = kTopDaric2AlertPeripheralOtpCtrl,
  [kTopDaric2AlertIdOtpCtrlFatalPrimOtpAlert] = kTopDaric2AlertPeripheralOtpCtrl,
  [kTopDaric2AlertIdOtpCtrlRecovPrimOtpAlert] = kTopDaric2AlertPeripheralOtpCtrl,
  [kTopDaric2AlertIdLcCtrlFatalProgError] = kTopDaric2AlertPeripheralLcCtrl,
  [kTopDaric2AlertIdLcCtrlFatalStateError] = kTopDaric2AlertPeripheralLcCtrl,
  [kTopDaric2AlertIdLcCtrlFatalBusIntegError] = kTopDaric2AlertPeripheralLcCtrl,
  [kTopDaric2AlertIdPwrmgrAonFatalFault] = kTopDaric2AlertPeripheralPwrmgrAon,
  [kTopDaric2AlertIdRstmgrAonFatalFault] = kTopDaric2AlertPeripheralRstmgrAon,
  [kTopDaric2AlertIdRstmgrAonFatalCnstyFault] = kTopDaric2AlertPeripheralRstmgrAon,
  [kTopDaric2AlertIdClkmgrAonRecovFault] = kTopDaric2AlertPeripheralClkmgrAon,
  [kTopDaric2AlertIdClkmgrAonFatalFault] = kTopDaric2AlertPeripheralClkmgrAon,
  [kTopDaric2AlertIdPinmuxAonFatalFault] = kTopDaric2AlertPeripheralPinmuxAon,
  [kTopDaric2AlertIdAonTimerAonFatalFault] = kTopDaric2AlertPeripheralAonTimerAon,
  [kTopDaric2AlertIdSocProxyFatalAlertIntg] = kTopDaric2AlertPeripheralSocProxy,
  [kTopDaric2AlertIdSocProxyFatalAlertExternal0] = kTopDaric2AlertPeripheralSocProxy,
  [kTopDaric2AlertIdSocProxyFatalAlertExternal1] = kTopDaric2AlertPeripheralSocProxy,
  [kTopDaric2AlertIdSocProxyFatalAlertExternal2] = kTopDaric2AlertPeripheralSocProxy,
  [kTopDaric2AlertIdSocProxyFatalAlertExternal3] = kTopDaric2AlertPeripheralSocProxy,
  [kTopDaric2AlertIdSocProxyFatalAlertExternal4] = kTopDaric2AlertPeripheralSocProxy,
  [kTopDaric2AlertIdSocProxyFatalAlertExternal5] = kTopDaric2AlertPeripheralSocProxy,
  [kTopDaric2AlertIdSocProxyFatalAlertExternal6] = kTopDaric2AlertPeripheralSocProxy,
  [kTopDaric2AlertIdSocProxyFatalAlertExternal7] = kTopDaric2AlertPeripheralSocProxy,
  [kTopDaric2AlertIdSocProxyFatalAlertExternal8] = kTopDaric2AlertPeripheralSocProxy,
  [kTopDaric2AlertIdSocProxyFatalAlertExternal9] = kTopDaric2AlertPeripheralSocProxy,
  [kTopDaric2AlertIdSocProxyFatalAlertExternal10] = kTopDaric2AlertPeripheralSocProxy,
  [kTopDaric2AlertIdSocProxyFatalAlertExternal11] = kTopDaric2AlertPeripheralSocProxy,
  [kTopDaric2AlertIdSocProxyFatalAlertExternal12] = kTopDaric2AlertPeripheralSocProxy,
  [kTopDaric2AlertIdSocProxyFatalAlertExternal13] = kTopDaric2AlertPeripheralSocProxy,
  [kTopDaric2AlertIdSocProxyFatalAlertExternal14] = kTopDaric2AlertPeripheralSocProxy,
  [kTopDaric2AlertIdSocProxyFatalAlertExternal15] = kTopDaric2AlertPeripheralSocProxy,
  [kTopDaric2AlertIdSocProxyFatalAlertExternal16] = kTopDaric2AlertPeripheralSocProxy,
  [kTopDaric2AlertIdSocProxyFatalAlertExternal17] = kTopDaric2AlertPeripheralSocProxy,
  [kTopDaric2AlertIdSocProxyFatalAlertExternal18] = kTopDaric2AlertPeripheralSocProxy,
  [kTopDaric2AlertIdSocProxyFatalAlertExternal19] = kTopDaric2AlertPeripheralSocProxy,
  [kTopDaric2AlertIdSocProxyFatalAlertExternal20] = kTopDaric2AlertPeripheralSocProxy,
  [kTopDaric2AlertIdSocProxyFatalAlertExternal21] = kTopDaric2AlertPeripheralSocProxy,
  [kTopDaric2AlertIdSocProxyFatalAlertExternal22] = kTopDaric2AlertPeripheralSocProxy,
  [kTopDaric2AlertIdSocProxyFatalAlertExternal23] = kTopDaric2AlertPeripheralSocProxy,
  [kTopDaric2AlertIdSocProxyRecovAlertExternal0] = kTopDaric2AlertPeripheralSocProxy,
  [kTopDaric2AlertIdSocProxyRecovAlertExternal1] = kTopDaric2AlertPeripheralSocProxy,
  [kTopDaric2AlertIdSocProxyRecovAlertExternal2] = kTopDaric2AlertPeripheralSocProxy,
  [kTopDaric2AlertIdSocProxyRecovAlertExternal3] = kTopDaric2AlertPeripheralSocProxy,
  [kTopDaric2AlertIdSramCtrlRetAonFatalError] = kTopDaric2AlertPeripheralSramCtrlRetAon,
  [kTopDaric2AlertIdRvDmFatalFault] = kTopDaric2AlertPeripheralRvDm,
  [kTopDaric2AlertIdRvPlicFatalFault] = kTopDaric2AlertPeripheralRvPlic,
  [kTopDaric2AlertIdAesRecovCtrlUpdateErr] = kTopDaric2AlertPeripheralAes,
  [kTopDaric2AlertIdAesFatalFault] = kTopDaric2AlertPeripheralAes,
  [kTopDaric2AlertIdHmacFatalFault] = kTopDaric2AlertPeripheralHmac,
  [kTopDaric2AlertIdKmacRecovOperationErr] = kTopDaric2AlertPeripheralKmac,
  [kTopDaric2AlertIdKmacFatalFaultErr] = kTopDaric2AlertPeripheralKmac,
  [kTopDaric2AlertIdOtbnFatal] = kTopDaric2AlertPeripheralOtbn,
  [kTopDaric2AlertIdOtbnRecov] = kTopDaric2AlertPeripheralOtbn,
  [kTopDaric2AlertIdKeymgrDpeRecovOperationErr] = kTopDaric2AlertPeripheralKeymgrDpe,
  [kTopDaric2AlertIdKeymgrDpeFatalFaultErr] = kTopDaric2AlertPeripheralKeymgrDpe,
  [kTopDaric2AlertIdCsrngRecovAlert] = kTopDaric2AlertPeripheralCsrng,
  [kTopDaric2AlertIdCsrngFatalAlert] = kTopDaric2AlertPeripheralCsrng,
  [kTopDaric2AlertIdEdn0RecovAlert] = kTopDaric2AlertPeripheralEdn0,
  [kTopDaric2AlertIdEdn0FatalAlert] = kTopDaric2AlertPeripheralEdn0,
  [kTopDaric2AlertIdEdn1RecovAlert] = kTopDaric2AlertPeripheralEdn1,
  [kTopDaric2AlertIdEdn1FatalAlert] = kTopDaric2AlertPeripheralEdn1,
  [kTopDaric2AlertIdSramCtrlMainFatalError] = kTopDaric2AlertPeripheralSramCtrlMain,
  [kTopDaric2AlertIdSramCtrlMboxFatalError] = kTopDaric2AlertPeripheralSramCtrlMbox,
  [kTopDaric2AlertIdRomCtrl0Fatal] = kTopDaric2AlertPeripheralRomCtrl0,
  [kTopDaric2AlertIdRomCtrl1Fatal] = kTopDaric2AlertPeripheralRomCtrl1,
  [kTopDaric2AlertIdDmaFatalFault] = kTopDaric2AlertPeripheralDma,
  [kTopDaric2AlertIdMbx0FatalFault] = kTopDaric2AlertPeripheralMbx0,
  [kTopDaric2AlertIdMbx0RecovFault] = kTopDaric2AlertPeripheralMbx0,
  [kTopDaric2AlertIdMbx1FatalFault] = kTopDaric2AlertPeripheralMbx1,
  [kTopDaric2AlertIdMbx1RecovFault] = kTopDaric2AlertPeripheralMbx1,
  [kTopDaric2AlertIdMbx2FatalFault] = kTopDaric2AlertPeripheralMbx2,
  [kTopDaric2AlertIdMbx2RecovFault] = kTopDaric2AlertPeripheralMbx2,
  [kTopDaric2AlertIdMbx3FatalFault] = kTopDaric2AlertPeripheralMbx3,
  [kTopDaric2AlertIdMbx3RecovFault] = kTopDaric2AlertPeripheralMbx3,
  [kTopDaric2AlertIdMbx4FatalFault] = kTopDaric2AlertPeripheralMbx4,
  [kTopDaric2AlertIdMbx4RecovFault] = kTopDaric2AlertPeripheralMbx4,
  [kTopDaric2AlertIdMbx5FatalFault] = kTopDaric2AlertPeripheralMbx5,
  [kTopDaric2AlertIdMbx5RecovFault] = kTopDaric2AlertPeripheralMbx5,
  [kTopDaric2AlertIdMbx6FatalFault] = kTopDaric2AlertPeripheralMbx6,
  [kTopDaric2AlertIdMbx6RecovFault] = kTopDaric2AlertPeripheralMbx6,
  [kTopDaric2AlertIdMbxJtagFatalFault] = kTopDaric2AlertPeripheralMbxJtag,
  [kTopDaric2AlertIdMbxJtagRecovFault] = kTopDaric2AlertPeripheralMbxJtag,
  [kTopDaric2AlertIdSocDbgCtrlFatalFault] = kTopDaric2AlertPeripheralSocDbgCtrl,
  [kTopDaric2AlertIdSocDbgCtrlRecovCtrlUpdateErr] = kTopDaric2AlertPeripheralSocDbgCtrl,
  [kTopDaric2AlertIdRaclCtrlFatalFault] = kTopDaric2AlertPeripheralRaclCtrl,
  [kTopDaric2AlertIdRaclCtrlRecovCtrlUpdateErr] = kTopDaric2AlertPeripheralRaclCtrl,
  [kTopDaric2AlertIdAcRangeCheckRecovCtrlUpdateErr] = kTopDaric2AlertPeripheralAcRangeCheck,
  [kTopDaric2AlertIdAcRangeCheckFatalFault] = kTopDaric2AlertPeripheralAcRangeCheck,
  [kTopDaric2AlertIdRvCoreIbexFatalSwErr] = kTopDaric2AlertPeripheralRvCoreIbex,
  [kTopDaric2AlertIdRvCoreIbexRecovSwErr] = kTopDaric2AlertPeripheralRvCoreIbex,
  [kTopDaric2AlertIdRvCoreIbexFatalHwErr] = kTopDaric2AlertPeripheralRvCoreIbex,
  [kTopDaric2AlertIdRvCoreIbexRecovHwErr] = kTopDaric2AlertPeripheralRvCoreIbex,
};

/**
 * PLIC Interrupt Source to Peripheral Map
 *
 * This array is a mapping from `top_daric2_plic_irq_id_t` to
 * `top_daric2_plic_peripheral_t`.
 */
const top_daric2_plic_peripheral_t
    top_daric2_plic_interrupt_for_peripheral[129] = {
  [kTopDaric2PlicIrqIdNone] = kTopDaric2PlicPeripheralUnknown,
  [kTopDaric2PlicIrqIdUart0TxWatermark] = kTopDaric2PlicPeripheralUart0,
  [kTopDaric2PlicIrqIdUart0RxWatermark] = kTopDaric2PlicPeripheralUart0,
  [kTopDaric2PlicIrqIdUart0TxDone] = kTopDaric2PlicPeripheralUart0,
  [kTopDaric2PlicIrqIdUart0RxOverflow] = kTopDaric2PlicPeripheralUart0,
  [kTopDaric2PlicIrqIdUart0RxFrameErr] = kTopDaric2PlicPeripheralUart0,
  [kTopDaric2PlicIrqIdUart0RxBreakErr] = kTopDaric2PlicPeripheralUart0,
  [kTopDaric2PlicIrqIdUart0RxTimeout] = kTopDaric2PlicPeripheralUart0,
  [kTopDaric2PlicIrqIdUart0RxParityErr] = kTopDaric2PlicPeripheralUart0,
  [kTopDaric2PlicIrqIdUart0TxEmpty] = kTopDaric2PlicPeripheralUart0,
  [kTopDaric2PlicIrqIdGpioGpio0] = kTopDaric2PlicPeripheralGpio,
  [kTopDaric2PlicIrqIdGpioGpio1] = kTopDaric2PlicPeripheralGpio,
  [kTopDaric2PlicIrqIdGpioGpio2] = kTopDaric2PlicPeripheralGpio,
  [kTopDaric2PlicIrqIdGpioGpio3] = kTopDaric2PlicPeripheralGpio,
  [kTopDaric2PlicIrqIdGpioGpio4] = kTopDaric2PlicPeripheralGpio,
  [kTopDaric2PlicIrqIdGpioGpio5] = kTopDaric2PlicPeripheralGpio,
  [kTopDaric2PlicIrqIdGpioGpio6] = kTopDaric2PlicPeripheralGpio,
  [kTopDaric2PlicIrqIdGpioGpio7] = kTopDaric2PlicPeripheralGpio,
  [kTopDaric2PlicIrqIdGpioGpio8] = kTopDaric2PlicPeripheralGpio,
  [kTopDaric2PlicIrqIdGpioGpio9] = kTopDaric2PlicPeripheralGpio,
  [kTopDaric2PlicIrqIdGpioGpio10] = kTopDaric2PlicPeripheralGpio,
  [kTopDaric2PlicIrqIdGpioGpio11] = kTopDaric2PlicPeripheralGpio,
  [kTopDaric2PlicIrqIdGpioGpio12] = kTopDaric2PlicPeripheralGpio,
  [kTopDaric2PlicIrqIdGpioGpio13] = kTopDaric2PlicPeripheralGpio,
  [kTopDaric2PlicIrqIdGpioGpio14] = kTopDaric2PlicPeripheralGpio,
  [kTopDaric2PlicIrqIdGpioGpio15] = kTopDaric2PlicPeripheralGpio,
  [kTopDaric2PlicIrqIdGpioGpio16] = kTopDaric2PlicPeripheralGpio,
  [kTopDaric2PlicIrqIdGpioGpio17] = kTopDaric2PlicPeripheralGpio,
  [kTopDaric2PlicIrqIdGpioGpio18] = kTopDaric2PlicPeripheralGpio,
  [kTopDaric2PlicIrqIdGpioGpio19] = kTopDaric2PlicPeripheralGpio,
  [kTopDaric2PlicIrqIdGpioGpio20] = kTopDaric2PlicPeripheralGpio,
  [kTopDaric2PlicIrqIdGpioGpio21] = kTopDaric2PlicPeripheralGpio,
  [kTopDaric2PlicIrqIdGpioGpio22] = kTopDaric2PlicPeripheralGpio,
  [kTopDaric2PlicIrqIdGpioGpio23] = kTopDaric2PlicPeripheralGpio,
  [kTopDaric2PlicIrqIdGpioGpio24] = kTopDaric2PlicPeripheralGpio,
  [kTopDaric2PlicIrqIdGpioGpio25] = kTopDaric2PlicPeripheralGpio,
  [kTopDaric2PlicIrqIdGpioGpio26] = kTopDaric2PlicPeripheralGpio,
  [kTopDaric2PlicIrqIdGpioGpio27] = kTopDaric2PlicPeripheralGpio,
  [kTopDaric2PlicIrqIdGpioGpio28] = kTopDaric2PlicPeripheralGpio,
  [kTopDaric2PlicIrqIdGpioGpio29] = kTopDaric2PlicPeripheralGpio,
  [kTopDaric2PlicIrqIdGpioGpio30] = kTopDaric2PlicPeripheralGpio,
  [kTopDaric2PlicIrqIdGpioGpio31] = kTopDaric2PlicPeripheralGpio,
  [kTopDaric2PlicIrqIdRvTimerTimerExpiredHart0Timer0] = kTopDaric2PlicPeripheralRvTimer,
  [kTopDaric2PlicIrqIdOtpCtrlOtpOperationDone] = kTopDaric2PlicPeripheralOtpCtrl,
  [kTopDaric2PlicIrqIdOtpCtrlOtpError] = kTopDaric2PlicPeripheralOtpCtrl,
  [kTopDaric2PlicIrqIdAlertHandlerClassa] = kTopDaric2PlicPeripheralAlertHandler,
  [kTopDaric2PlicIrqIdAlertHandlerClassb] = kTopDaric2PlicPeripheralAlertHandler,
  [kTopDaric2PlicIrqIdAlertHandlerClassc] = kTopDaric2PlicPeripheralAlertHandler,
  [kTopDaric2PlicIrqIdAlertHandlerClassd] = kTopDaric2PlicPeripheralAlertHandler,
  [kTopDaric2PlicIrqIdPwrmgrAonWakeup] = kTopDaric2PlicPeripheralPwrmgrAon,
  [kTopDaric2PlicIrqIdAonTimerAonWkupTimerExpired] = kTopDaric2PlicPeripheralAonTimerAon,
  [kTopDaric2PlicIrqIdAonTimerAonWdogTimerBark] = kTopDaric2PlicPeripheralAonTimerAon,
  [kTopDaric2PlicIrqIdSocProxyExternal0] = kTopDaric2PlicPeripheralSocProxy,
  [kTopDaric2PlicIrqIdSocProxyExternal1] = kTopDaric2PlicPeripheralSocProxy,
  [kTopDaric2PlicIrqIdSocProxyExternal2] = kTopDaric2PlicPeripheralSocProxy,
  [kTopDaric2PlicIrqIdSocProxyExternal3] = kTopDaric2PlicPeripheralSocProxy,
  [kTopDaric2PlicIrqIdSocProxyExternal4] = kTopDaric2PlicPeripheralSocProxy,
  [kTopDaric2PlicIrqIdSocProxyExternal5] = kTopDaric2PlicPeripheralSocProxy,
  [kTopDaric2PlicIrqIdSocProxyExternal6] = kTopDaric2PlicPeripheralSocProxy,
  [kTopDaric2PlicIrqIdSocProxyExternal7] = kTopDaric2PlicPeripheralSocProxy,
  [kTopDaric2PlicIrqIdSocProxyExternal8] = kTopDaric2PlicPeripheralSocProxy,
  [kTopDaric2PlicIrqIdSocProxyExternal9] = kTopDaric2PlicPeripheralSocProxy,
  [kTopDaric2PlicIrqIdSocProxyExternal10] = kTopDaric2PlicPeripheralSocProxy,
  [kTopDaric2PlicIrqIdSocProxyExternal11] = kTopDaric2PlicPeripheralSocProxy,
  [kTopDaric2PlicIrqIdSocProxyExternal12] = kTopDaric2PlicPeripheralSocProxy,
  [kTopDaric2PlicIrqIdSocProxyExternal13] = kTopDaric2PlicPeripheralSocProxy,
  [kTopDaric2PlicIrqIdSocProxyExternal14] = kTopDaric2PlicPeripheralSocProxy,
  [kTopDaric2PlicIrqIdSocProxyExternal15] = kTopDaric2PlicPeripheralSocProxy,
  [kTopDaric2PlicIrqIdSocProxyExternal16] = kTopDaric2PlicPeripheralSocProxy,
  [kTopDaric2PlicIrqIdSocProxyExternal17] = kTopDaric2PlicPeripheralSocProxy,
  [kTopDaric2PlicIrqIdSocProxyExternal18] = kTopDaric2PlicPeripheralSocProxy,
  [kTopDaric2PlicIrqIdSocProxyExternal19] = kTopDaric2PlicPeripheralSocProxy,
  [kTopDaric2PlicIrqIdSocProxyExternal20] = kTopDaric2PlicPeripheralSocProxy,
  [kTopDaric2PlicIrqIdSocProxyExternal21] = kTopDaric2PlicPeripheralSocProxy,
  [kTopDaric2PlicIrqIdSocProxyExternal22] = kTopDaric2PlicPeripheralSocProxy,
  [kTopDaric2PlicIrqIdSocProxyExternal23] = kTopDaric2PlicPeripheralSocProxy,
  [kTopDaric2PlicIrqIdSocProxyExternal24] = kTopDaric2PlicPeripheralSocProxy,
  [kTopDaric2PlicIrqIdSocProxyExternal25] = kTopDaric2PlicPeripheralSocProxy,
  [kTopDaric2PlicIrqIdSocProxyExternal26] = kTopDaric2PlicPeripheralSocProxy,
  [kTopDaric2PlicIrqIdSocProxyExternal27] = kTopDaric2PlicPeripheralSocProxy,
  [kTopDaric2PlicIrqIdSocProxyExternal28] = kTopDaric2PlicPeripheralSocProxy,
  [kTopDaric2PlicIrqIdSocProxyExternal29] = kTopDaric2PlicPeripheralSocProxy,
  [kTopDaric2PlicIrqIdSocProxyExternal30] = kTopDaric2PlicPeripheralSocProxy,
  [kTopDaric2PlicIrqIdSocProxyExternal31] = kTopDaric2PlicPeripheralSocProxy,
  [kTopDaric2PlicIrqIdHmacHmacDone] = kTopDaric2PlicPeripheralHmac,
  [kTopDaric2PlicIrqIdHmacFifoEmpty] = kTopDaric2PlicPeripheralHmac,
  [kTopDaric2PlicIrqIdHmacHmacErr] = kTopDaric2PlicPeripheralHmac,
  [kTopDaric2PlicIrqIdKmacKmacDone] = kTopDaric2PlicPeripheralKmac,
  [kTopDaric2PlicIrqIdKmacFifoEmpty] = kTopDaric2PlicPeripheralKmac,
  [kTopDaric2PlicIrqIdKmacKmacErr] = kTopDaric2PlicPeripheralKmac,
  [kTopDaric2PlicIrqIdOtbnDone] = kTopDaric2PlicPeripheralOtbn,
  [kTopDaric2PlicIrqIdKeymgrDpeOpDone] = kTopDaric2PlicPeripheralKeymgrDpe,
  [kTopDaric2PlicIrqIdCsrngCsCmdReqDone] = kTopDaric2PlicPeripheralCsrng,
  [kTopDaric2PlicIrqIdCsrngCsEntropyReq] = kTopDaric2PlicPeripheralCsrng,
  [kTopDaric2PlicIrqIdCsrngCsHwInstExc] = kTopDaric2PlicPeripheralCsrng,
  [kTopDaric2PlicIrqIdCsrngCsFatalErr] = kTopDaric2PlicPeripheralCsrng,
  [kTopDaric2PlicIrqIdEdn0EdnCmdReqDone] = kTopDaric2PlicPeripheralEdn0,
  [kTopDaric2PlicIrqIdEdn0EdnFatalErr] = kTopDaric2PlicPeripheralEdn0,
  [kTopDaric2PlicIrqIdEdn1EdnCmdReqDone] = kTopDaric2PlicPeripheralEdn1,
  [kTopDaric2PlicIrqIdEdn1EdnFatalErr] = kTopDaric2PlicPeripheralEdn1,
  [kTopDaric2PlicIrqIdDmaDmaDone] = kTopDaric2PlicPeripheralDma,
  [kTopDaric2PlicIrqIdDmaDmaChunkDone] = kTopDaric2PlicPeripheralDma,
  [kTopDaric2PlicIrqIdDmaDmaError] = kTopDaric2PlicPeripheralDma,
  [kTopDaric2PlicIrqIdMbx0MbxReady] = kTopDaric2PlicPeripheralMbx0,
  [kTopDaric2PlicIrqIdMbx0MbxAbort] = kTopDaric2PlicPeripheralMbx0,
  [kTopDaric2PlicIrqIdMbx0MbxError] = kTopDaric2PlicPeripheralMbx0,
  [kTopDaric2PlicIrqIdMbx1MbxReady] = kTopDaric2PlicPeripheralMbx1,
  [kTopDaric2PlicIrqIdMbx1MbxAbort] = kTopDaric2PlicPeripheralMbx1,
  [kTopDaric2PlicIrqIdMbx1MbxError] = kTopDaric2PlicPeripheralMbx1,
  [kTopDaric2PlicIrqIdMbx2MbxReady] = kTopDaric2PlicPeripheralMbx2,
  [kTopDaric2PlicIrqIdMbx2MbxAbort] = kTopDaric2PlicPeripheralMbx2,
  [kTopDaric2PlicIrqIdMbx2MbxError] = kTopDaric2PlicPeripheralMbx2,
  [kTopDaric2PlicIrqIdMbx3MbxReady] = kTopDaric2PlicPeripheralMbx3,
  [kTopDaric2PlicIrqIdMbx3MbxAbort] = kTopDaric2PlicPeripheralMbx3,
  [kTopDaric2PlicIrqIdMbx3MbxError] = kTopDaric2PlicPeripheralMbx3,
  [kTopDaric2PlicIrqIdMbx4MbxReady] = kTopDaric2PlicPeripheralMbx4,
  [kTopDaric2PlicIrqIdMbx4MbxAbort] = kTopDaric2PlicPeripheralMbx4,
  [kTopDaric2PlicIrqIdMbx4MbxError] = kTopDaric2PlicPeripheralMbx4,
  [kTopDaric2PlicIrqIdMbx5MbxReady] = kTopDaric2PlicPeripheralMbx5,
  [kTopDaric2PlicIrqIdMbx5MbxAbort] = kTopDaric2PlicPeripheralMbx5,
  [kTopDaric2PlicIrqIdMbx5MbxError] = kTopDaric2PlicPeripheralMbx5,
  [kTopDaric2PlicIrqIdMbx6MbxReady] = kTopDaric2PlicPeripheralMbx6,
  [kTopDaric2PlicIrqIdMbx6MbxAbort] = kTopDaric2PlicPeripheralMbx6,
  [kTopDaric2PlicIrqIdMbx6MbxError] = kTopDaric2PlicPeripheralMbx6,
  [kTopDaric2PlicIrqIdMbxJtagMbxReady] = kTopDaric2PlicPeripheralMbxJtag,
  [kTopDaric2PlicIrqIdMbxJtagMbxAbort] = kTopDaric2PlicPeripheralMbxJtag,
  [kTopDaric2PlicIrqIdMbxJtagMbxError] = kTopDaric2PlicPeripheralMbxJtag,
  [kTopDaric2PlicIrqIdRaclCtrlRaclError] = kTopDaric2PlicPeripheralRaclCtrl,
  [kTopDaric2PlicIrqIdAcRangeCheckDenyCntReached] = kTopDaric2PlicPeripheralAcRangeCheck,
};
