// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0

// This file was generated automatically.
// Please do not modify content of this file directly.
// File generated by using template: "toplevel.rs.tpl"
// To regenerate this file follow OpenTitan topgen documentations.

#![allow(dead_code)]

//! This file contains enums and consts for use within the Rust codebase.
//!
//! These definitions are for information that depends on the top-specific chip
//! configuration, which includes:
//! - Device Memory Information (for Peripherals and Memory)
//! - PLIC Interrupt ID Names and Source Mappings
//! - Alert ID Names and Source Mappings
//! - Pinmux Pin/Select Names
//! - Power Manager Wakeups

use core::convert::TryFrom;

/// Peripheral base address for uart0 in top daric2.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const UART0_BASE_ADDR: usize = 0x30010000;

/// Peripheral size for uart0 in top daric2.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #UART0_BASE_ADDR and
/// `UART0_BASE_ADDR + UART0_SIZE_BYTES`.
pub const UART0_SIZE_BYTES: usize = 0x40;

/// Peripheral base address for gpio in top daric2.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const GPIO_BASE_ADDR: usize = 0x30000000;

/// Peripheral size for gpio in top daric2.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #GPIO_BASE_ADDR and
/// `GPIO_BASE_ADDR + GPIO_SIZE_BYTES`.
pub const GPIO_SIZE_BYTES: usize = 0x100;

/// Peripheral base address for rv_timer in top daric2.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const RV_TIMER_BASE_ADDR: usize = 0x30100000;

/// Peripheral size for rv_timer in top daric2.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #RV_TIMER_BASE_ADDR and
/// `RV_TIMER_BASE_ADDR + RV_TIMER_SIZE_BYTES`.
pub const RV_TIMER_SIZE_BYTES: usize = 0x200;

/// Peripheral base address for core device on otp_ctrl in top daric2.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const OTP_CTRL_CORE_BASE_ADDR: usize = 0x30130000;

/// Peripheral size for core device on otp_ctrl in top daric2.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #OTP_CTRL_CORE_BASE_ADDR and
/// `OTP_CTRL_CORE_BASE_ADDR + OTP_CTRL_CORE_SIZE_BYTES`.
pub const OTP_CTRL_CORE_SIZE_BYTES: usize = 0x8000;

/// Peripheral base address for otp_macro in top daric2.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const OTP_MACRO_BASE_ADDR: usize = 0x30140000;

/// Peripheral size for otp_macro in top daric2.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #OTP_MACRO_BASE_ADDR and
/// `OTP_MACRO_BASE_ADDR + OTP_MACRO_SIZE_BYTES`.
pub const OTP_MACRO_SIZE_BYTES: usize = 0x20;

/// Peripheral base address for regs device on lc_ctrl in top daric2.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const LC_CTRL_REGS_BASE_ADDR: usize = 0x30150000;

/// Peripheral size for regs device on lc_ctrl in top daric2.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #LC_CTRL_REGS_BASE_ADDR and
/// `LC_CTRL_REGS_BASE_ADDR + LC_CTRL_REGS_SIZE_BYTES`.
pub const LC_CTRL_REGS_SIZE_BYTES: usize = 0x100;

/// Peripheral base address for alert_handler in top daric2.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const ALERT_HANDLER_BASE_ADDR: usize = 0x30160000;

/// Peripheral size for alert_handler in top daric2.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #ALERT_HANDLER_BASE_ADDR and
/// `ALERT_HANDLER_BASE_ADDR + ALERT_HANDLER_SIZE_BYTES`.
pub const ALERT_HANDLER_SIZE_BYTES: usize = 0x800;

/// Peripheral base address for pwrmgr_aon in top daric2.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const PWRMGR_AON_BASE_ADDR: usize = 0x30400000;

/// Peripheral size for pwrmgr_aon in top daric2.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #PWRMGR_AON_BASE_ADDR and
/// `PWRMGR_AON_BASE_ADDR + PWRMGR_AON_SIZE_BYTES`.
pub const PWRMGR_AON_SIZE_BYTES: usize = 0x80;

/// Peripheral base address for rstmgr_aon in top daric2.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const RSTMGR_AON_BASE_ADDR: usize = 0x30410000;

/// Peripheral size for rstmgr_aon in top daric2.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #RSTMGR_AON_BASE_ADDR and
/// `RSTMGR_AON_BASE_ADDR + RSTMGR_AON_SIZE_BYTES`.
pub const RSTMGR_AON_SIZE_BYTES: usize = 0x40;

/// Peripheral base address for clkmgr_aon in top daric2.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const CLKMGR_AON_BASE_ADDR: usize = 0x30420000;

/// Peripheral size for clkmgr_aon in top daric2.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #CLKMGR_AON_BASE_ADDR and
/// `CLKMGR_AON_BASE_ADDR + CLKMGR_AON_SIZE_BYTES`.
pub const CLKMGR_AON_SIZE_BYTES: usize = 0x40;

/// Peripheral base address for pinmux_aon in top daric2.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const PINMUX_AON_BASE_ADDR: usize = 0x30460000;

/// Peripheral size for pinmux_aon in top daric2.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #PINMUX_AON_BASE_ADDR and
/// `PINMUX_AON_BASE_ADDR + PINMUX_AON_SIZE_BYTES`.
pub const PINMUX_AON_SIZE_BYTES: usize = 0x800;

/// Peripheral base address for aon_timer_aon in top daric2.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const AON_TIMER_AON_BASE_ADDR: usize = 0x30470000;

/// Peripheral size for aon_timer_aon in top daric2.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #AON_TIMER_AON_BASE_ADDR and
/// `AON_TIMER_AON_BASE_ADDR + AON_TIMER_AON_SIZE_BYTES`.
pub const AON_TIMER_AON_SIZE_BYTES: usize = 0x40;

/// Peripheral base address for core device on soc_proxy in top daric2.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const SOC_PROXY_CORE_BASE_ADDR: usize = 0x22030000;

/// Peripheral size for core device on soc_proxy in top daric2.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #SOC_PROXY_CORE_BASE_ADDR and
/// `SOC_PROXY_CORE_BASE_ADDR + SOC_PROXY_CORE_SIZE_BYTES`.
pub const SOC_PROXY_CORE_SIZE_BYTES: usize = 0x10;

/// Peripheral base address for ctn device on soc_proxy in top daric2.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const SOC_PROXY_CTN_BASE_ADDR: usize = 0x40000000;

/// Peripheral size for ctn device on soc_proxy in top daric2.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #SOC_PROXY_CTN_BASE_ADDR and
/// `SOC_PROXY_CTN_BASE_ADDR + SOC_PROXY_CTN_SIZE_BYTES`.
pub const SOC_PROXY_CTN_SIZE_BYTES: usize = 0x40000000;

/// Peripheral base address for regs device on sram_ctrl_ret_aon in top daric2.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const SRAM_CTRL_RET_AON_REGS_BASE_ADDR: usize = 0x30500000;

/// Peripheral size for regs device on sram_ctrl_ret_aon in top daric2.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #SRAM_CTRL_RET_AON_REGS_BASE_ADDR and
/// `SRAM_CTRL_RET_AON_REGS_BASE_ADDR + SRAM_CTRL_RET_AON_REGS_SIZE_BYTES`.
pub const SRAM_CTRL_RET_AON_REGS_SIZE_BYTES: usize = 0x40;

/// Peripheral base address for ram device on sram_ctrl_ret_aon in top daric2.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const SRAM_CTRL_RET_AON_RAM_BASE_ADDR: usize = 0x30600000;

/// Peripheral size for ram device on sram_ctrl_ret_aon in top daric2.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #SRAM_CTRL_RET_AON_RAM_BASE_ADDR and
/// `SRAM_CTRL_RET_AON_RAM_BASE_ADDR + SRAM_CTRL_RET_AON_RAM_SIZE_BYTES`.
pub const SRAM_CTRL_RET_AON_RAM_SIZE_BYTES: usize = 0x1000;

/// Peripheral base address for regs device on rv_dm in top daric2.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const RV_DM_REGS_BASE_ADDR: usize = 0x21200000;

/// Peripheral size for regs device on rv_dm in top daric2.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #RV_DM_REGS_BASE_ADDR and
/// `RV_DM_REGS_BASE_ADDR + RV_DM_REGS_SIZE_BYTES`.
pub const RV_DM_REGS_SIZE_BYTES: usize = 0x10;

/// Peripheral base address for mem device on rv_dm in top daric2.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const RV_DM_MEM_BASE_ADDR: usize = 0x40000;

/// Peripheral size for mem device on rv_dm in top daric2.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #RV_DM_MEM_BASE_ADDR and
/// `RV_DM_MEM_BASE_ADDR + RV_DM_MEM_SIZE_BYTES`.
pub const RV_DM_MEM_SIZE_BYTES: usize = 0x1000;

/// Peripheral base address for rv_plic in top daric2.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const RV_PLIC_BASE_ADDR: usize = 0x28000000;

/// Peripheral size for rv_plic in top daric2.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #RV_PLIC_BASE_ADDR and
/// `RV_PLIC_BASE_ADDR + RV_PLIC_SIZE_BYTES`.
pub const RV_PLIC_SIZE_BYTES: usize = 0x8000000;

/// Peripheral base address for aes in top daric2.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const AES_BASE_ADDR: usize = 0x21100000;

/// Peripheral size for aes in top daric2.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #AES_BASE_ADDR and
/// `AES_BASE_ADDR + AES_SIZE_BYTES`.
pub const AES_SIZE_BYTES: usize = 0x100;

/// Peripheral base address for hmac in top daric2.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const HMAC_BASE_ADDR: usize = 0x21110000;

/// Peripheral size for hmac in top daric2.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #HMAC_BASE_ADDR and
/// `HMAC_BASE_ADDR + HMAC_SIZE_BYTES`.
pub const HMAC_SIZE_BYTES: usize = 0x2000;

/// Peripheral base address for kmac in top daric2.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const KMAC_BASE_ADDR: usize = 0x21120000;

/// Peripheral size for kmac in top daric2.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #KMAC_BASE_ADDR and
/// `KMAC_BASE_ADDR + KMAC_SIZE_BYTES`.
pub const KMAC_SIZE_BYTES: usize = 0x1000;

/// Peripheral base address for otbn in top daric2.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const OTBN_BASE_ADDR: usize = 0x21130000;

/// Peripheral size for otbn in top daric2.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #OTBN_BASE_ADDR and
/// `OTBN_BASE_ADDR + OTBN_SIZE_BYTES`.
pub const OTBN_SIZE_BYTES: usize = 0x10000;

/// Peripheral base address for keymgr_dpe in top daric2.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const KEYMGR_DPE_BASE_ADDR: usize = 0x21140000;

/// Peripheral size for keymgr_dpe in top daric2.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #KEYMGR_DPE_BASE_ADDR and
/// `KEYMGR_DPE_BASE_ADDR + KEYMGR_DPE_SIZE_BYTES`.
pub const KEYMGR_DPE_SIZE_BYTES: usize = 0x100;

/// Peripheral base address for csrng in top daric2.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const CSRNG_BASE_ADDR: usize = 0x21150000;

/// Peripheral size for csrng in top daric2.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #CSRNG_BASE_ADDR and
/// `CSRNG_BASE_ADDR + CSRNG_SIZE_BYTES`.
pub const CSRNG_SIZE_BYTES: usize = 0x80;

/// Peripheral base address for edn0 in top daric2.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const EDN0_BASE_ADDR: usize = 0x21170000;

/// Peripheral size for edn0 in top daric2.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #EDN0_BASE_ADDR and
/// `EDN0_BASE_ADDR + EDN0_SIZE_BYTES`.
pub const EDN0_SIZE_BYTES: usize = 0x80;

/// Peripheral base address for edn1 in top daric2.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const EDN1_BASE_ADDR: usize = 0x21180000;

/// Peripheral size for edn1 in top daric2.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #EDN1_BASE_ADDR and
/// `EDN1_BASE_ADDR + EDN1_SIZE_BYTES`.
pub const EDN1_SIZE_BYTES: usize = 0x80;

/// Peripheral base address for regs device on sram_ctrl_main in top daric2.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const SRAM_CTRL_MAIN_REGS_BASE_ADDR: usize = 0x211C0000;

/// Peripheral size for regs device on sram_ctrl_main in top daric2.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #SRAM_CTRL_MAIN_REGS_BASE_ADDR and
/// `SRAM_CTRL_MAIN_REGS_BASE_ADDR + SRAM_CTRL_MAIN_REGS_SIZE_BYTES`.
pub const SRAM_CTRL_MAIN_REGS_SIZE_BYTES: usize = 0x40;

/// Peripheral base address for ram device on sram_ctrl_main in top daric2.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const SRAM_CTRL_MAIN_RAM_BASE_ADDR: usize = 0x10000000;

/// Peripheral size for ram device on sram_ctrl_main in top daric2.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #SRAM_CTRL_MAIN_RAM_BASE_ADDR and
/// `SRAM_CTRL_MAIN_RAM_BASE_ADDR + SRAM_CTRL_MAIN_RAM_SIZE_BYTES`.
pub const SRAM_CTRL_MAIN_RAM_SIZE_BYTES: usize = 0x10000;

/// Peripheral base address for regs device on sram_ctrl_mbox in top daric2.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const SRAM_CTRL_MBOX_REGS_BASE_ADDR: usize = 0x211D0000;

/// Peripheral size for regs device on sram_ctrl_mbox in top daric2.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #SRAM_CTRL_MBOX_REGS_BASE_ADDR and
/// `SRAM_CTRL_MBOX_REGS_BASE_ADDR + SRAM_CTRL_MBOX_REGS_SIZE_BYTES`.
pub const SRAM_CTRL_MBOX_REGS_SIZE_BYTES: usize = 0x40;

/// Peripheral base address for ram device on sram_ctrl_mbox in top daric2.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const SRAM_CTRL_MBOX_RAM_BASE_ADDR: usize = 0x11000000;

/// Peripheral size for ram device on sram_ctrl_mbox in top daric2.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #SRAM_CTRL_MBOX_RAM_BASE_ADDR and
/// `SRAM_CTRL_MBOX_RAM_BASE_ADDR + SRAM_CTRL_MBOX_RAM_SIZE_BYTES`.
pub const SRAM_CTRL_MBOX_RAM_SIZE_BYTES: usize = 0x1000;

/// Peripheral base address for regs device on rom_ctrl0 in top daric2.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const ROM_CTRL0_REGS_BASE_ADDR: usize = 0x211E0000;

/// Peripheral size for regs device on rom_ctrl0 in top daric2.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #ROM_CTRL0_REGS_BASE_ADDR and
/// `ROM_CTRL0_REGS_BASE_ADDR + ROM_CTRL0_REGS_SIZE_BYTES`.
pub const ROM_CTRL0_REGS_SIZE_BYTES: usize = 0x80;

/// Peripheral base address for rom device on rom_ctrl0 in top daric2.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const ROM_CTRL0_ROM_BASE_ADDR: usize = 0x8000;

/// Peripheral size for rom device on rom_ctrl0 in top daric2.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #ROM_CTRL0_ROM_BASE_ADDR and
/// `ROM_CTRL0_ROM_BASE_ADDR + ROM_CTRL0_ROM_SIZE_BYTES`.
pub const ROM_CTRL0_ROM_SIZE_BYTES: usize = 0x8000;

/// Peripheral base address for regs device on rom_ctrl1 in top daric2.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const ROM_CTRL1_REGS_BASE_ADDR: usize = 0x211E1000;

/// Peripheral size for regs device on rom_ctrl1 in top daric2.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #ROM_CTRL1_REGS_BASE_ADDR and
/// `ROM_CTRL1_REGS_BASE_ADDR + ROM_CTRL1_REGS_SIZE_BYTES`.
pub const ROM_CTRL1_REGS_SIZE_BYTES: usize = 0x80;

/// Peripheral base address for rom device on rom_ctrl1 in top daric2.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const ROM_CTRL1_ROM_BASE_ADDR: usize = 0x20000;

/// Peripheral size for rom device on rom_ctrl1 in top daric2.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #ROM_CTRL1_ROM_BASE_ADDR and
/// `ROM_CTRL1_ROM_BASE_ADDR + ROM_CTRL1_ROM_SIZE_BYTES`.
pub const ROM_CTRL1_ROM_SIZE_BYTES: usize = 0x10000;

/// Peripheral base address for dma in top daric2.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const DMA_BASE_ADDR: usize = 0x22010000;

/// Peripheral size for dma in top daric2.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #DMA_BASE_ADDR and
/// `DMA_BASE_ADDR + DMA_SIZE_BYTES`.
pub const DMA_SIZE_BYTES: usize = 0x200;

/// Peripheral base address for core device on mbx0 in top daric2.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const MBX0_CORE_BASE_ADDR: usize = 0x22000000;

/// Peripheral size for core device on mbx0 in top daric2.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #MBX0_CORE_BASE_ADDR and
/// `MBX0_CORE_BASE_ADDR + MBX0_CORE_SIZE_BYTES`.
pub const MBX0_CORE_SIZE_BYTES: usize = 0x80;

/// Peripheral base address for core device on mbx1 in top daric2.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const MBX1_CORE_BASE_ADDR: usize = 0x22000100;

/// Peripheral size for core device on mbx1 in top daric2.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #MBX1_CORE_BASE_ADDR and
/// `MBX1_CORE_BASE_ADDR + MBX1_CORE_SIZE_BYTES`.
pub const MBX1_CORE_SIZE_BYTES: usize = 0x80;

/// Peripheral base address for core device on mbx2 in top daric2.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const MBX2_CORE_BASE_ADDR: usize = 0x22000200;

/// Peripheral size for core device on mbx2 in top daric2.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #MBX2_CORE_BASE_ADDR and
/// `MBX2_CORE_BASE_ADDR + MBX2_CORE_SIZE_BYTES`.
pub const MBX2_CORE_SIZE_BYTES: usize = 0x80;

/// Peripheral base address for core device on mbx3 in top daric2.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const MBX3_CORE_BASE_ADDR: usize = 0x22000300;

/// Peripheral size for core device on mbx3 in top daric2.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #MBX3_CORE_BASE_ADDR and
/// `MBX3_CORE_BASE_ADDR + MBX3_CORE_SIZE_BYTES`.
pub const MBX3_CORE_SIZE_BYTES: usize = 0x80;

/// Peripheral base address for core device on mbx4 in top daric2.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const MBX4_CORE_BASE_ADDR: usize = 0x22000400;

/// Peripheral size for core device on mbx4 in top daric2.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #MBX4_CORE_BASE_ADDR and
/// `MBX4_CORE_BASE_ADDR + MBX4_CORE_SIZE_BYTES`.
pub const MBX4_CORE_SIZE_BYTES: usize = 0x80;

/// Peripheral base address for core device on mbx5 in top daric2.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const MBX5_CORE_BASE_ADDR: usize = 0x22000500;

/// Peripheral size for core device on mbx5 in top daric2.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #MBX5_CORE_BASE_ADDR and
/// `MBX5_CORE_BASE_ADDR + MBX5_CORE_SIZE_BYTES`.
pub const MBX5_CORE_SIZE_BYTES: usize = 0x80;

/// Peripheral base address for core device on mbx6 in top daric2.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const MBX6_CORE_BASE_ADDR: usize = 0x22000600;

/// Peripheral size for core device on mbx6 in top daric2.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #MBX6_CORE_BASE_ADDR and
/// `MBX6_CORE_BASE_ADDR + MBX6_CORE_SIZE_BYTES`.
pub const MBX6_CORE_SIZE_BYTES: usize = 0x80;

/// Peripheral base address for core device on mbx_jtag in top daric2.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const MBX_JTAG_CORE_BASE_ADDR: usize = 0x22000800;

/// Peripheral size for core device on mbx_jtag in top daric2.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #MBX_JTAG_CORE_BASE_ADDR and
/// `MBX_JTAG_CORE_BASE_ADDR + MBX_JTAG_CORE_SIZE_BYTES`.
pub const MBX_JTAG_CORE_SIZE_BYTES: usize = 0x80;

/// Peripheral base address for core device on soc_dbg_ctrl in top daric2.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const SOC_DBG_CTRL_CORE_BASE_ADDR: usize = 0x30170000;

/// Peripheral size for core device on soc_dbg_ctrl in top daric2.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #SOC_DBG_CTRL_CORE_BASE_ADDR and
/// `SOC_DBG_CTRL_CORE_BASE_ADDR + SOC_DBG_CTRL_CORE_SIZE_BYTES`.
pub const SOC_DBG_CTRL_CORE_SIZE_BYTES: usize = 0x20;

/// Peripheral base address for cfg device on rv_core_ibex in top daric2.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const RV_CORE_IBEX_CFG_BASE_ADDR: usize = 0x211F0000;

/// Peripheral size for cfg device on rv_core_ibex in top daric2.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #RV_CORE_IBEX_CFG_BASE_ADDR and
/// `RV_CORE_IBEX_CFG_BASE_ADDR + RV_CORE_IBEX_CFG_SIZE_BYTES`.
pub const RV_CORE_IBEX_CFG_SIZE_BYTES: usize = 0x800;

/// Memory base address for ctn in top daric2.
pub const CTN_BASE_ADDR: usize = 0x40000000;

/// Memory size for ctn in top daric2.
pub const CTN_SIZE_BYTES: usize = 0x40000000;

/// Memory base address for ram_ret_aon in top daric2.
pub const RAM_RET_AON_BASE_ADDR: usize = 0x30600000;

/// Memory size for ram_ret_aon in top daric2.
pub const RAM_RET_AON_SIZE_BYTES: usize = 0x1000;

/// Memory base address for ram_main in top daric2.
pub const RAM_MAIN_BASE_ADDR: usize = 0x10000000;

/// Memory size for ram_main in top daric2.
pub const RAM_MAIN_SIZE_BYTES: usize = 0x10000;

/// Memory base address for ram_mbox in top daric2.
pub const RAM_MBOX_BASE_ADDR: usize = 0x11000000;

/// Memory size for ram_mbox in top daric2.
pub const RAM_MBOX_SIZE_BYTES: usize = 0x1000;

/// Memory base address for rom0 in top daric2.
pub const ROM0_BASE_ADDR: usize = 0x8000;

/// Memory size for rom0 in top daric2.
pub const ROM0_SIZE_BYTES: usize = 0x8000;

/// Memory base address for rom1 in top daric2.
pub const ROM1_BASE_ADDR: usize = 0x20000;

/// Memory size for rom1 in top daric2.
pub const ROM1_SIZE_BYTES: usize = 0x10000;

/// PLIC Interrupt Source Peripheral.
///
/// Enumeration used to determine which peripheral asserted the corresponding
/// interrupt.
#[derive(Copy, Clone, PartialEq, Eq)]
#[repr(u32)]
pub enum PlicPeripheral {
    /// Unknown Peripheral
    Unknown = 0,
    /// uart0
    Uart0 = 1,
    /// gpio
    Gpio = 2,
    /// rv_timer
    RvTimer = 3,
    /// otp_ctrl
    OtpCtrl = 4,
    /// alert_handler
    AlertHandler = 5,
    /// pwrmgr_aon
    PwrmgrAon = 6,
    /// aon_timer_aon
    AonTimerAon = 7,
    /// soc_proxy
    SocProxy = 8,
    /// hmac
    Hmac = 9,
    /// kmac
    Kmac = 10,
    /// otbn
    Otbn = 11,
    /// keymgr_dpe
    KeymgrDpe = 12,
    /// csrng
    Csrng = 13,
    /// edn0
    Edn0 = 14,
    /// edn1
    Edn1 = 15,
    /// dma
    Dma = 16,
    /// mbx0
    Mbx0 = 17,
    /// mbx1
    Mbx1 = 18,
    /// mbx2
    Mbx2 = 19,
    /// mbx3
    Mbx3 = 20,
    /// mbx4
    Mbx4 = 21,
    /// mbx5
    Mbx5 = 22,
    /// mbx6
    Mbx6 = 23,
    /// mbx_jtag
    MbxJtag = 24,
    /// racl_ctrl
    RaclCtrl = 25,
    /// ac_range_check
    AcRangeCheck = 26,
}

impl TryFrom<u32> for PlicPeripheral {
    type Error = u32;
    fn try_from(val: u32) -> Result<Self, Self::Error> {
        match val {
            0 => Ok(Self::Unknown),
            1 => Ok(Self::Uart0),
            2 => Ok(Self::Gpio),
            3 => Ok(Self::RvTimer),
            4 => Ok(Self::OtpCtrl),
            5 => Ok(Self::AlertHandler),
            6 => Ok(Self::PwrmgrAon),
            7 => Ok(Self::AonTimerAon),
            8 => Ok(Self::SocProxy),
            9 => Ok(Self::Hmac),
            10 => Ok(Self::Kmac),
            11 => Ok(Self::Otbn),
            12 => Ok(Self::KeymgrDpe),
            13 => Ok(Self::Csrng),
            14 => Ok(Self::Edn0),
            15 => Ok(Self::Edn1),
            16 => Ok(Self::Dma),
            17 => Ok(Self::Mbx0),
            18 => Ok(Self::Mbx1),
            19 => Ok(Self::Mbx2),
            20 => Ok(Self::Mbx3),
            21 => Ok(Self::Mbx4),
            22 => Ok(Self::Mbx5),
            23 => Ok(Self::Mbx6),
            24 => Ok(Self::MbxJtag),
            25 => Ok(Self::RaclCtrl),
            26 => Ok(Self::AcRangeCheck),
            _ => Err(val),
        }
    }
}

/// PLIC Interrupt Source.
///
/// Enumeration of all PLIC interrupt sources. The interrupt sources belonging to
/// the same peripheral are guaranteed to be consecutive.
#[derive(Copy, Clone, PartialEq, Eq)]
#[repr(u32)]
pub enum PlicIrqId {
    /// No Interrupt
    None = 0,
    /// uart0_tx_watermark
    Uart0TxWatermark = 1,
    /// uart0_rx_watermark
    Uart0RxWatermark = 2,
    /// uart0_tx_done
    Uart0TxDone = 3,
    /// uart0_rx_overflow
    Uart0RxOverflow = 4,
    /// uart0_rx_frame_err
    Uart0RxFrameErr = 5,
    /// uart0_rx_break_err
    Uart0RxBreakErr = 6,
    /// uart0_rx_timeout
    Uart0RxTimeout = 7,
    /// uart0_rx_parity_err
    Uart0RxParityErr = 8,
    /// uart0_tx_empty
    Uart0TxEmpty = 9,
    /// gpio_gpio 0
    GpioGpio0 = 10,
    /// gpio_gpio 1
    GpioGpio1 = 11,
    /// gpio_gpio 2
    GpioGpio2 = 12,
    /// gpio_gpio 3
    GpioGpio3 = 13,
    /// gpio_gpio 4
    GpioGpio4 = 14,
    /// gpio_gpio 5
    GpioGpio5 = 15,
    /// gpio_gpio 6
    GpioGpio6 = 16,
    /// gpio_gpio 7
    GpioGpio7 = 17,
    /// gpio_gpio 8
    GpioGpio8 = 18,
    /// gpio_gpio 9
    GpioGpio9 = 19,
    /// gpio_gpio 10
    GpioGpio10 = 20,
    /// gpio_gpio 11
    GpioGpio11 = 21,
    /// gpio_gpio 12
    GpioGpio12 = 22,
    /// gpio_gpio 13
    GpioGpio13 = 23,
    /// gpio_gpio 14
    GpioGpio14 = 24,
    /// gpio_gpio 15
    GpioGpio15 = 25,
    /// gpio_gpio 16
    GpioGpio16 = 26,
    /// gpio_gpio 17
    GpioGpio17 = 27,
    /// gpio_gpio 18
    GpioGpio18 = 28,
    /// gpio_gpio 19
    GpioGpio19 = 29,
    /// gpio_gpio 20
    GpioGpio20 = 30,
    /// gpio_gpio 21
    GpioGpio21 = 31,
    /// gpio_gpio 22
    GpioGpio22 = 32,
    /// gpio_gpio 23
    GpioGpio23 = 33,
    /// gpio_gpio 24
    GpioGpio24 = 34,
    /// gpio_gpio 25
    GpioGpio25 = 35,
    /// gpio_gpio 26
    GpioGpio26 = 36,
    /// gpio_gpio 27
    GpioGpio27 = 37,
    /// gpio_gpio 28
    GpioGpio28 = 38,
    /// gpio_gpio 29
    GpioGpio29 = 39,
    /// gpio_gpio 30
    GpioGpio30 = 40,
    /// gpio_gpio 31
    GpioGpio31 = 41,
    /// rv_timer_timer_expired_hart0_timer0
    RvTimerTimerExpiredHart0Timer0 = 42,
    /// otp_ctrl_otp_operation_done
    OtpCtrlOtpOperationDone = 43,
    /// otp_ctrl_otp_error
    OtpCtrlOtpError = 44,
    /// alert_handler_classa
    AlertHandlerClassa = 45,
    /// alert_handler_classb
    AlertHandlerClassb = 46,
    /// alert_handler_classc
    AlertHandlerClassc = 47,
    /// alert_handler_classd
    AlertHandlerClassd = 48,
    /// pwrmgr_aon_wakeup
    PwrmgrAonWakeup = 49,
    /// aon_timer_aon_wkup_timer_expired
    AonTimerAonWkupTimerExpired = 50,
    /// aon_timer_aon_wdog_timer_bark
    AonTimerAonWdogTimerBark = 51,
    /// soc_proxy_external 0
    SocProxyExternal0 = 52,
    /// soc_proxy_external 1
    SocProxyExternal1 = 53,
    /// soc_proxy_external 2
    SocProxyExternal2 = 54,
    /// soc_proxy_external 3
    SocProxyExternal3 = 55,
    /// soc_proxy_external 4
    SocProxyExternal4 = 56,
    /// soc_proxy_external 5
    SocProxyExternal5 = 57,
    /// soc_proxy_external 6
    SocProxyExternal6 = 58,
    /// soc_proxy_external 7
    SocProxyExternal7 = 59,
    /// soc_proxy_external 8
    SocProxyExternal8 = 60,
    /// soc_proxy_external 9
    SocProxyExternal9 = 61,
    /// soc_proxy_external 10
    SocProxyExternal10 = 62,
    /// soc_proxy_external 11
    SocProxyExternal11 = 63,
    /// soc_proxy_external 12
    SocProxyExternal12 = 64,
    /// soc_proxy_external 13
    SocProxyExternal13 = 65,
    /// soc_proxy_external 14
    SocProxyExternal14 = 66,
    /// soc_proxy_external 15
    SocProxyExternal15 = 67,
    /// soc_proxy_external 16
    SocProxyExternal16 = 68,
    /// soc_proxy_external 17
    SocProxyExternal17 = 69,
    /// soc_proxy_external 18
    SocProxyExternal18 = 70,
    /// soc_proxy_external 19
    SocProxyExternal19 = 71,
    /// soc_proxy_external 20
    SocProxyExternal20 = 72,
    /// soc_proxy_external 21
    SocProxyExternal21 = 73,
    /// soc_proxy_external 22
    SocProxyExternal22 = 74,
    /// soc_proxy_external 23
    SocProxyExternal23 = 75,
    /// soc_proxy_external 24
    SocProxyExternal24 = 76,
    /// soc_proxy_external 25
    SocProxyExternal25 = 77,
    /// soc_proxy_external 26
    SocProxyExternal26 = 78,
    /// soc_proxy_external 27
    SocProxyExternal27 = 79,
    /// soc_proxy_external 28
    SocProxyExternal28 = 80,
    /// soc_proxy_external 29
    SocProxyExternal29 = 81,
    /// soc_proxy_external 30
    SocProxyExternal30 = 82,
    /// soc_proxy_external 31
    SocProxyExternal31 = 83,
    /// hmac_hmac_done
    HmacHmacDone = 84,
    /// hmac_fifo_empty
    HmacFifoEmpty = 85,
    /// hmac_hmac_err
    HmacHmacErr = 86,
    /// kmac_kmac_done
    KmacKmacDone = 87,
    /// kmac_fifo_empty
    KmacFifoEmpty = 88,
    /// kmac_kmac_err
    KmacKmacErr = 89,
    /// otbn_done
    OtbnDone = 90,
    /// keymgr_dpe_op_done
    KeymgrDpeOpDone = 91,
    /// csrng_cs_cmd_req_done
    CsrngCsCmdReqDone = 92,
    /// csrng_cs_entropy_req
    CsrngCsEntropyReq = 93,
    /// csrng_cs_hw_inst_exc
    CsrngCsHwInstExc = 94,
    /// csrng_cs_fatal_err
    CsrngCsFatalErr = 95,
    /// edn0_edn_cmd_req_done
    Edn0EdnCmdReqDone = 96,
    /// edn0_edn_fatal_err
    Edn0EdnFatalErr = 97,
    /// edn1_edn_cmd_req_done
    Edn1EdnCmdReqDone = 98,
    /// edn1_edn_fatal_err
    Edn1EdnFatalErr = 99,
    /// dma_dma_done
    DmaDmaDone = 100,
    /// dma_dma_chunk_done
    DmaDmaChunkDone = 101,
    /// dma_dma_error
    DmaDmaError = 102,
    /// mbx0_mbx_ready
    Mbx0MbxReady = 103,
    /// mbx0_mbx_abort
    Mbx0MbxAbort = 104,
    /// mbx0_mbx_error
    Mbx0MbxError = 105,
    /// mbx1_mbx_ready
    Mbx1MbxReady = 106,
    /// mbx1_mbx_abort
    Mbx1MbxAbort = 107,
    /// mbx1_mbx_error
    Mbx1MbxError = 108,
    /// mbx2_mbx_ready
    Mbx2MbxReady = 109,
    /// mbx2_mbx_abort
    Mbx2MbxAbort = 110,
    /// mbx2_mbx_error
    Mbx2MbxError = 111,
    /// mbx3_mbx_ready
    Mbx3MbxReady = 112,
    /// mbx3_mbx_abort
    Mbx3MbxAbort = 113,
    /// mbx3_mbx_error
    Mbx3MbxError = 114,
    /// mbx4_mbx_ready
    Mbx4MbxReady = 115,
    /// mbx4_mbx_abort
    Mbx4MbxAbort = 116,
    /// mbx4_mbx_error
    Mbx4MbxError = 117,
    /// mbx5_mbx_ready
    Mbx5MbxReady = 118,
    /// mbx5_mbx_abort
    Mbx5MbxAbort = 119,
    /// mbx5_mbx_error
    Mbx5MbxError = 120,
    /// mbx6_mbx_ready
    Mbx6MbxReady = 121,
    /// mbx6_mbx_abort
    Mbx6MbxAbort = 122,
    /// mbx6_mbx_error
    Mbx6MbxError = 123,
    /// mbx_jtag_mbx_ready
    MbxJtagMbxReady = 124,
    /// mbx_jtag_mbx_abort
    MbxJtagMbxAbort = 125,
    /// mbx_jtag_mbx_error
    MbxJtagMbxError = 126,
    /// racl_ctrl_racl_error
    RaclCtrlRaclError = 127,
    /// ac_range_check_deny_cnt_reached
    AcRangeCheckDenyCntReached = 128,
}

impl TryFrom<u32> for PlicIrqId {
    type Error = u32;
    fn try_from(val: u32) -> Result<Self, Self::Error> {
        match val {
            0 => Ok(Self::None),
            1 => Ok(Self::Uart0TxWatermark),
            2 => Ok(Self::Uart0RxWatermark),
            3 => Ok(Self::Uart0TxDone),
            4 => Ok(Self::Uart0RxOverflow),
            5 => Ok(Self::Uart0RxFrameErr),
            6 => Ok(Self::Uart0RxBreakErr),
            7 => Ok(Self::Uart0RxTimeout),
            8 => Ok(Self::Uart0RxParityErr),
            9 => Ok(Self::Uart0TxEmpty),
            10 => Ok(Self::GpioGpio0),
            11 => Ok(Self::GpioGpio1),
            12 => Ok(Self::GpioGpio2),
            13 => Ok(Self::GpioGpio3),
            14 => Ok(Self::GpioGpio4),
            15 => Ok(Self::GpioGpio5),
            16 => Ok(Self::GpioGpio6),
            17 => Ok(Self::GpioGpio7),
            18 => Ok(Self::GpioGpio8),
            19 => Ok(Self::GpioGpio9),
            20 => Ok(Self::GpioGpio10),
            21 => Ok(Self::GpioGpio11),
            22 => Ok(Self::GpioGpio12),
            23 => Ok(Self::GpioGpio13),
            24 => Ok(Self::GpioGpio14),
            25 => Ok(Self::GpioGpio15),
            26 => Ok(Self::GpioGpio16),
            27 => Ok(Self::GpioGpio17),
            28 => Ok(Self::GpioGpio18),
            29 => Ok(Self::GpioGpio19),
            30 => Ok(Self::GpioGpio20),
            31 => Ok(Self::GpioGpio21),
            32 => Ok(Self::GpioGpio22),
            33 => Ok(Self::GpioGpio23),
            34 => Ok(Self::GpioGpio24),
            35 => Ok(Self::GpioGpio25),
            36 => Ok(Self::GpioGpio26),
            37 => Ok(Self::GpioGpio27),
            38 => Ok(Self::GpioGpio28),
            39 => Ok(Self::GpioGpio29),
            40 => Ok(Self::GpioGpio30),
            41 => Ok(Self::GpioGpio31),
            42 => Ok(Self::RvTimerTimerExpiredHart0Timer0),
            43 => Ok(Self::OtpCtrlOtpOperationDone),
            44 => Ok(Self::OtpCtrlOtpError),
            45 => Ok(Self::AlertHandlerClassa),
            46 => Ok(Self::AlertHandlerClassb),
            47 => Ok(Self::AlertHandlerClassc),
            48 => Ok(Self::AlertHandlerClassd),
            49 => Ok(Self::PwrmgrAonWakeup),
            50 => Ok(Self::AonTimerAonWkupTimerExpired),
            51 => Ok(Self::AonTimerAonWdogTimerBark),
            52 => Ok(Self::SocProxyExternal0),
            53 => Ok(Self::SocProxyExternal1),
            54 => Ok(Self::SocProxyExternal2),
            55 => Ok(Self::SocProxyExternal3),
            56 => Ok(Self::SocProxyExternal4),
            57 => Ok(Self::SocProxyExternal5),
            58 => Ok(Self::SocProxyExternal6),
            59 => Ok(Self::SocProxyExternal7),
            60 => Ok(Self::SocProxyExternal8),
            61 => Ok(Self::SocProxyExternal9),
            62 => Ok(Self::SocProxyExternal10),
            63 => Ok(Self::SocProxyExternal11),
            64 => Ok(Self::SocProxyExternal12),
            65 => Ok(Self::SocProxyExternal13),
            66 => Ok(Self::SocProxyExternal14),
            67 => Ok(Self::SocProxyExternal15),
            68 => Ok(Self::SocProxyExternal16),
            69 => Ok(Self::SocProxyExternal17),
            70 => Ok(Self::SocProxyExternal18),
            71 => Ok(Self::SocProxyExternal19),
            72 => Ok(Self::SocProxyExternal20),
            73 => Ok(Self::SocProxyExternal21),
            74 => Ok(Self::SocProxyExternal22),
            75 => Ok(Self::SocProxyExternal23),
            76 => Ok(Self::SocProxyExternal24),
            77 => Ok(Self::SocProxyExternal25),
            78 => Ok(Self::SocProxyExternal26),
            79 => Ok(Self::SocProxyExternal27),
            80 => Ok(Self::SocProxyExternal28),
            81 => Ok(Self::SocProxyExternal29),
            82 => Ok(Self::SocProxyExternal30),
            83 => Ok(Self::SocProxyExternal31),
            84 => Ok(Self::HmacHmacDone),
            85 => Ok(Self::HmacFifoEmpty),
            86 => Ok(Self::HmacHmacErr),
            87 => Ok(Self::KmacKmacDone),
            88 => Ok(Self::KmacFifoEmpty),
            89 => Ok(Self::KmacKmacErr),
            90 => Ok(Self::OtbnDone),
            91 => Ok(Self::KeymgrDpeOpDone),
            92 => Ok(Self::CsrngCsCmdReqDone),
            93 => Ok(Self::CsrngCsEntropyReq),
            94 => Ok(Self::CsrngCsHwInstExc),
            95 => Ok(Self::CsrngCsFatalErr),
            96 => Ok(Self::Edn0EdnCmdReqDone),
            97 => Ok(Self::Edn0EdnFatalErr),
            98 => Ok(Self::Edn1EdnCmdReqDone),
            99 => Ok(Self::Edn1EdnFatalErr),
            100 => Ok(Self::DmaDmaDone),
            101 => Ok(Self::DmaDmaChunkDone),
            102 => Ok(Self::DmaDmaError),
            103 => Ok(Self::Mbx0MbxReady),
            104 => Ok(Self::Mbx0MbxAbort),
            105 => Ok(Self::Mbx0MbxError),
            106 => Ok(Self::Mbx1MbxReady),
            107 => Ok(Self::Mbx1MbxAbort),
            108 => Ok(Self::Mbx1MbxError),
            109 => Ok(Self::Mbx2MbxReady),
            110 => Ok(Self::Mbx2MbxAbort),
            111 => Ok(Self::Mbx2MbxError),
            112 => Ok(Self::Mbx3MbxReady),
            113 => Ok(Self::Mbx3MbxAbort),
            114 => Ok(Self::Mbx3MbxError),
            115 => Ok(Self::Mbx4MbxReady),
            116 => Ok(Self::Mbx4MbxAbort),
            117 => Ok(Self::Mbx4MbxError),
            118 => Ok(Self::Mbx5MbxReady),
            119 => Ok(Self::Mbx5MbxAbort),
            120 => Ok(Self::Mbx5MbxError),
            121 => Ok(Self::Mbx6MbxReady),
            122 => Ok(Self::Mbx6MbxAbort),
            123 => Ok(Self::Mbx6MbxError),
            124 => Ok(Self::MbxJtagMbxReady),
            125 => Ok(Self::MbxJtagMbxAbort),
            126 => Ok(Self::MbxJtagMbxError),
            127 => Ok(Self::RaclCtrlRaclError),
            128 => Ok(Self::AcRangeCheckDenyCntReached),
            _ => Err(val),
        }
    }
}

/// PLIC Interrupt Target.
///
/// Enumeration used to determine which set of IE, CC, threshold registers to
/// access for a given interrupt target.
#[derive(Copy, Clone, PartialEq, Eq)]
#[repr(u32)]
pub enum PlicTarget {
    /// Ibex Core 0
    Ibex0 = 0,
}

/// PLIC Interrupt Source to Peripheral Map
///
/// This array is a mapping from `PlicIrqId` to
/// `PlicPeripheral`.
pub const PLIC_INTERRUPT_FOR_PERIPHERAL: [PlicPeripheral; 129] = [
    // None -> PlicPeripheral::Unknown
    PlicPeripheral::Unknown,
    // Uart0TxWatermark -> PlicPeripheral::Uart0
    PlicPeripheral::Uart0,
    // Uart0RxWatermark -> PlicPeripheral::Uart0
    PlicPeripheral::Uart0,
    // Uart0TxDone -> PlicPeripheral::Uart0
    PlicPeripheral::Uart0,
    // Uart0RxOverflow -> PlicPeripheral::Uart0
    PlicPeripheral::Uart0,
    // Uart0RxFrameErr -> PlicPeripheral::Uart0
    PlicPeripheral::Uart0,
    // Uart0RxBreakErr -> PlicPeripheral::Uart0
    PlicPeripheral::Uart0,
    // Uart0RxTimeout -> PlicPeripheral::Uart0
    PlicPeripheral::Uart0,
    // Uart0RxParityErr -> PlicPeripheral::Uart0
    PlicPeripheral::Uart0,
    // Uart0TxEmpty -> PlicPeripheral::Uart0
    PlicPeripheral::Uart0,
    // GpioGpio0 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio1 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio2 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio3 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio4 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio5 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio6 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio7 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio8 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio9 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio10 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio11 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio12 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio13 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio14 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio15 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio16 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio17 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio18 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio19 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio20 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio21 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio22 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio23 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio24 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio25 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio26 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio27 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio28 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio29 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio30 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // GpioGpio31 -> PlicPeripheral::Gpio
    PlicPeripheral::Gpio,
    // RvTimerTimerExpiredHart0Timer0 -> PlicPeripheral::RvTimer
    PlicPeripheral::RvTimer,
    // OtpCtrlOtpOperationDone -> PlicPeripheral::OtpCtrl
    PlicPeripheral::OtpCtrl,
    // OtpCtrlOtpError -> PlicPeripheral::OtpCtrl
    PlicPeripheral::OtpCtrl,
    // AlertHandlerClassa -> PlicPeripheral::AlertHandler
    PlicPeripheral::AlertHandler,
    // AlertHandlerClassb -> PlicPeripheral::AlertHandler
    PlicPeripheral::AlertHandler,
    // AlertHandlerClassc -> PlicPeripheral::AlertHandler
    PlicPeripheral::AlertHandler,
    // AlertHandlerClassd -> PlicPeripheral::AlertHandler
    PlicPeripheral::AlertHandler,
    // PwrmgrAonWakeup -> PlicPeripheral::PwrmgrAon
    PlicPeripheral::PwrmgrAon,
    // AonTimerAonWkupTimerExpired -> PlicPeripheral::AonTimerAon
    PlicPeripheral::AonTimerAon,
    // AonTimerAonWdogTimerBark -> PlicPeripheral::AonTimerAon
    PlicPeripheral::AonTimerAon,
    // SocProxyExternal0 -> PlicPeripheral::SocProxy
    PlicPeripheral::SocProxy,
    // SocProxyExternal1 -> PlicPeripheral::SocProxy
    PlicPeripheral::SocProxy,
    // SocProxyExternal2 -> PlicPeripheral::SocProxy
    PlicPeripheral::SocProxy,
    // SocProxyExternal3 -> PlicPeripheral::SocProxy
    PlicPeripheral::SocProxy,
    // SocProxyExternal4 -> PlicPeripheral::SocProxy
    PlicPeripheral::SocProxy,
    // SocProxyExternal5 -> PlicPeripheral::SocProxy
    PlicPeripheral::SocProxy,
    // SocProxyExternal6 -> PlicPeripheral::SocProxy
    PlicPeripheral::SocProxy,
    // SocProxyExternal7 -> PlicPeripheral::SocProxy
    PlicPeripheral::SocProxy,
    // SocProxyExternal8 -> PlicPeripheral::SocProxy
    PlicPeripheral::SocProxy,
    // SocProxyExternal9 -> PlicPeripheral::SocProxy
    PlicPeripheral::SocProxy,
    // SocProxyExternal10 -> PlicPeripheral::SocProxy
    PlicPeripheral::SocProxy,
    // SocProxyExternal11 -> PlicPeripheral::SocProxy
    PlicPeripheral::SocProxy,
    // SocProxyExternal12 -> PlicPeripheral::SocProxy
    PlicPeripheral::SocProxy,
    // SocProxyExternal13 -> PlicPeripheral::SocProxy
    PlicPeripheral::SocProxy,
    // SocProxyExternal14 -> PlicPeripheral::SocProxy
    PlicPeripheral::SocProxy,
    // SocProxyExternal15 -> PlicPeripheral::SocProxy
    PlicPeripheral::SocProxy,
    // SocProxyExternal16 -> PlicPeripheral::SocProxy
    PlicPeripheral::SocProxy,
    // SocProxyExternal17 -> PlicPeripheral::SocProxy
    PlicPeripheral::SocProxy,
    // SocProxyExternal18 -> PlicPeripheral::SocProxy
    PlicPeripheral::SocProxy,
    // SocProxyExternal19 -> PlicPeripheral::SocProxy
    PlicPeripheral::SocProxy,
    // SocProxyExternal20 -> PlicPeripheral::SocProxy
    PlicPeripheral::SocProxy,
    // SocProxyExternal21 -> PlicPeripheral::SocProxy
    PlicPeripheral::SocProxy,
    // SocProxyExternal22 -> PlicPeripheral::SocProxy
    PlicPeripheral::SocProxy,
    // SocProxyExternal23 -> PlicPeripheral::SocProxy
    PlicPeripheral::SocProxy,
    // SocProxyExternal24 -> PlicPeripheral::SocProxy
    PlicPeripheral::SocProxy,
    // SocProxyExternal25 -> PlicPeripheral::SocProxy
    PlicPeripheral::SocProxy,
    // SocProxyExternal26 -> PlicPeripheral::SocProxy
    PlicPeripheral::SocProxy,
    // SocProxyExternal27 -> PlicPeripheral::SocProxy
    PlicPeripheral::SocProxy,
    // SocProxyExternal28 -> PlicPeripheral::SocProxy
    PlicPeripheral::SocProxy,
    // SocProxyExternal29 -> PlicPeripheral::SocProxy
    PlicPeripheral::SocProxy,
    // SocProxyExternal30 -> PlicPeripheral::SocProxy
    PlicPeripheral::SocProxy,
    // SocProxyExternal31 -> PlicPeripheral::SocProxy
    PlicPeripheral::SocProxy,
    // HmacHmacDone -> PlicPeripheral::Hmac
    PlicPeripheral::Hmac,
    // HmacFifoEmpty -> PlicPeripheral::Hmac
    PlicPeripheral::Hmac,
    // HmacHmacErr -> PlicPeripheral::Hmac
    PlicPeripheral::Hmac,
    // KmacKmacDone -> PlicPeripheral::Kmac
    PlicPeripheral::Kmac,
    // KmacFifoEmpty -> PlicPeripheral::Kmac
    PlicPeripheral::Kmac,
    // KmacKmacErr -> PlicPeripheral::Kmac
    PlicPeripheral::Kmac,
    // OtbnDone -> PlicPeripheral::Otbn
    PlicPeripheral::Otbn,
    // KeymgrDpeOpDone -> PlicPeripheral::KeymgrDpe
    PlicPeripheral::KeymgrDpe,
    // CsrngCsCmdReqDone -> PlicPeripheral::Csrng
    PlicPeripheral::Csrng,
    // CsrngCsEntropyReq -> PlicPeripheral::Csrng
    PlicPeripheral::Csrng,
    // CsrngCsHwInstExc -> PlicPeripheral::Csrng
    PlicPeripheral::Csrng,
    // CsrngCsFatalErr -> PlicPeripheral::Csrng
    PlicPeripheral::Csrng,
    // Edn0EdnCmdReqDone -> PlicPeripheral::Edn0
    PlicPeripheral::Edn0,
    // Edn0EdnFatalErr -> PlicPeripheral::Edn0
    PlicPeripheral::Edn0,
    // Edn1EdnCmdReqDone -> PlicPeripheral::Edn1
    PlicPeripheral::Edn1,
    // Edn1EdnFatalErr -> PlicPeripheral::Edn1
    PlicPeripheral::Edn1,
    // DmaDmaDone -> PlicPeripheral::Dma
    PlicPeripheral::Dma,
    // DmaDmaChunkDone -> PlicPeripheral::Dma
    PlicPeripheral::Dma,
    // DmaDmaError -> PlicPeripheral::Dma
    PlicPeripheral::Dma,
    // Mbx0MbxReady -> PlicPeripheral::Mbx0
    PlicPeripheral::Mbx0,
    // Mbx0MbxAbort -> PlicPeripheral::Mbx0
    PlicPeripheral::Mbx0,
    // Mbx0MbxError -> PlicPeripheral::Mbx0
    PlicPeripheral::Mbx0,
    // Mbx1MbxReady -> PlicPeripheral::Mbx1
    PlicPeripheral::Mbx1,
    // Mbx1MbxAbort -> PlicPeripheral::Mbx1
    PlicPeripheral::Mbx1,
    // Mbx1MbxError -> PlicPeripheral::Mbx1
    PlicPeripheral::Mbx1,
    // Mbx2MbxReady -> PlicPeripheral::Mbx2
    PlicPeripheral::Mbx2,
    // Mbx2MbxAbort -> PlicPeripheral::Mbx2
    PlicPeripheral::Mbx2,
    // Mbx2MbxError -> PlicPeripheral::Mbx2
    PlicPeripheral::Mbx2,
    // Mbx3MbxReady -> PlicPeripheral::Mbx3
    PlicPeripheral::Mbx3,
    // Mbx3MbxAbort -> PlicPeripheral::Mbx3
    PlicPeripheral::Mbx3,
    // Mbx3MbxError -> PlicPeripheral::Mbx3
    PlicPeripheral::Mbx3,
    // Mbx4MbxReady -> PlicPeripheral::Mbx4
    PlicPeripheral::Mbx4,
    // Mbx4MbxAbort -> PlicPeripheral::Mbx4
    PlicPeripheral::Mbx4,
    // Mbx4MbxError -> PlicPeripheral::Mbx4
    PlicPeripheral::Mbx4,
    // Mbx5MbxReady -> PlicPeripheral::Mbx5
    PlicPeripheral::Mbx5,
    // Mbx5MbxAbort -> PlicPeripheral::Mbx5
    PlicPeripheral::Mbx5,
    // Mbx5MbxError -> PlicPeripheral::Mbx5
    PlicPeripheral::Mbx5,
    // Mbx6MbxReady -> PlicPeripheral::Mbx6
    PlicPeripheral::Mbx6,
    // Mbx6MbxAbort -> PlicPeripheral::Mbx6
    PlicPeripheral::Mbx6,
    // Mbx6MbxError -> PlicPeripheral::Mbx6
    PlicPeripheral::Mbx6,
    // MbxJtagMbxReady -> PlicPeripheral::MbxJtag
    PlicPeripheral::MbxJtag,
    // MbxJtagMbxAbort -> PlicPeripheral::MbxJtag
    PlicPeripheral::MbxJtag,
    // MbxJtagMbxError -> PlicPeripheral::MbxJtag
    PlicPeripheral::MbxJtag,
    // RaclCtrlRaclError -> PlicPeripheral::RaclCtrl
    PlicPeripheral::RaclCtrl,
    // AcRangeCheckDenyCntReached -> PlicPeripheral::AcRangeCheck
    PlicPeripheral::AcRangeCheck,
];

/// Alert Handler Source Peripheral.
///
/// Enumeration used to determine which peripheral asserted the corresponding
/// alert.
#[derive(Copy, Clone, PartialEq, Eq)]
#[repr(u32)]
pub enum AlertPeripheral {
    /// External Peripheral
    External = 0,
    /// uart0
    Uart0 = 1,
    /// gpio
    Gpio = 2,
    /// rv_timer
    RvTimer = 3,
    /// otp_ctrl
    OtpCtrl = 4,
    /// lc_ctrl
    LcCtrl = 5,
    /// pwrmgr_aon
    PwrmgrAon = 6,
    /// rstmgr_aon
    RstmgrAon = 7,
    /// clkmgr_aon
    ClkmgrAon = 8,
    /// pinmux_aon
    PinmuxAon = 9,
    /// aon_timer_aon
    AonTimerAon = 10,
    /// soc_proxy
    SocProxy = 11,
    /// sram_ctrl_ret_aon
    SramCtrlRetAon = 12,
    /// rv_dm
    RvDm = 13,
    /// rv_plic
    RvPlic = 14,
    /// aes
    Aes = 15,
    /// hmac
    Hmac = 16,
    /// kmac
    Kmac = 17,
    /// otbn
    Otbn = 18,
    /// keymgr_dpe
    KeymgrDpe = 19,
    /// csrng
    Csrng = 20,
    /// edn0
    Edn0 = 21,
    /// edn1
    Edn1 = 22,
    /// sram_ctrl_main
    SramCtrlMain = 23,
    /// sram_ctrl_mbox
    SramCtrlMbox = 24,
    /// rom_ctrl0
    RomCtrl0 = 25,
    /// rom_ctrl1
    RomCtrl1 = 26,
    /// dma
    Dma = 27,
    /// mbx0
    Mbx0 = 28,
    /// mbx1
    Mbx1 = 29,
    /// mbx2
    Mbx2 = 30,
    /// mbx3
    Mbx3 = 31,
    /// mbx4
    Mbx4 = 32,
    /// mbx5
    Mbx5 = 33,
    /// mbx6
    Mbx6 = 34,
    /// mbx_jtag
    MbxJtag = 35,
    /// soc_dbg_ctrl
    SocDbgCtrl = 36,
    /// racl_ctrl
    RaclCtrl = 37,
    /// ac_range_check
    AcRangeCheck = 38,
    /// rv_core_ibex
    RvCoreIbex = 39,
}

/// Alert Handler Alert Source.
///
/// Enumeration of all Alert Handler Alert Sources. The alert sources belonging to
/// the same peripheral are guaranteed to be consecutive.
#[derive(Copy, Clone, PartialEq, Eq)]
#[repr(u32)]
pub enum AlertId {
    /// uart0_fatal_fault
    Uart0FatalFault = 0,
    /// gpio_fatal_fault
    GpioFatalFault = 1,
    /// rv_timer_fatal_fault
    RvTimerFatalFault = 2,
    /// otp_ctrl_fatal_macro_error
    OtpCtrlFatalMacroError = 3,
    /// otp_ctrl_fatal_check_error
    OtpCtrlFatalCheckError = 4,
    /// otp_ctrl_fatal_bus_integ_error
    OtpCtrlFatalBusIntegError = 5,
    /// otp_ctrl_fatal_prim_otp_alert
    OtpCtrlFatalPrimOtpAlert = 6,
    /// otp_ctrl_recov_prim_otp_alert
    OtpCtrlRecovPrimOtpAlert = 7,
    /// lc_ctrl_fatal_prog_error
    LcCtrlFatalProgError = 8,
    /// lc_ctrl_fatal_state_error
    LcCtrlFatalStateError = 9,
    /// lc_ctrl_fatal_bus_integ_error
    LcCtrlFatalBusIntegError = 10,
    /// pwrmgr_aon_fatal_fault
    PwrmgrAonFatalFault = 11,
    /// rstmgr_aon_fatal_fault
    RstmgrAonFatalFault = 12,
    /// rstmgr_aon_fatal_cnsty_fault
    RstmgrAonFatalCnstyFault = 13,
    /// clkmgr_aon_recov_fault
    ClkmgrAonRecovFault = 14,
    /// clkmgr_aon_fatal_fault
    ClkmgrAonFatalFault = 15,
    /// pinmux_aon_fatal_fault
    PinmuxAonFatalFault = 16,
    /// aon_timer_aon_fatal_fault
    AonTimerAonFatalFault = 17,
    /// soc_proxy_fatal_alert_intg
    SocProxyFatalAlertIntg = 18,
    /// soc_proxy_fatal_alert_external_0
    SocProxyFatalAlertExternal0 = 19,
    /// soc_proxy_fatal_alert_external_1
    SocProxyFatalAlertExternal1 = 20,
    /// soc_proxy_fatal_alert_external_2
    SocProxyFatalAlertExternal2 = 21,
    /// soc_proxy_fatal_alert_external_3
    SocProxyFatalAlertExternal3 = 22,
    /// soc_proxy_fatal_alert_external_4
    SocProxyFatalAlertExternal4 = 23,
    /// soc_proxy_fatal_alert_external_5
    SocProxyFatalAlertExternal5 = 24,
    /// soc_proxy_fatal_alert_external_6
    SocProxyFatalAlertExternal6 = 25,
    /// soc_proxy_fatal_alert_external_7
    SocProxyFatalAlertExternal7 = 26,
    /// soc_proxy_fatal_alert_external_8
    SocProxyFatalAlertExternal8 = 27,
    /// soc_proxy_fatal_alert_external_9
    SocProxyFatalAlertExternal9 = 28,
    /// soc_proxy_fatal_alert_external_10
    SocProxyFatalAlertExternal10 = 29,
    /// soc_proxy_fatal_alert_external_11
    SocProxyFatalAlertExternal11 = 30,
    /// soc_proxy_fatal_alert_external_12
    SocProxyFatalAlertExternal12 = 31,
    /// soc_proxy_fatal_alert_external_13
    SocProxyFatalAlertExternal13 = 32,
    /// soc_proxy_fatal_alert_external_14
    SocProxyFatalAlertExternal14 = 33,
    /// soc_proxy_fatal_alert_external_15
    SocProxyFatalAlertExternal15 = 34,
    /// soc_proxy_fatal_alert_external_16
    SocProxyFatalAlertExternal16 = 35,
    /// soc_proxy_fatal_alert_external_17
    SocProxyFatalAlertExternal17 = 36,
    /// soc_proxy_fatal_alert_external_18
    SocProxyFatalAlertExternal18 = 37,
    /// soc_proxy_fatal_alert_external_19
    SocProxyFatalAlertExternal19 = 38,
    /// soc_proxy_fatal_alert_external_20
    SocProxyFatalAlertExternal20 = 39,
    /// soc_proxy_fatal_alert_external_21
    SocProxyFatalAlertExternal21 = 40,
    /// soc_proxy_fatal_alert_external_22
    SocProxyFatalAlertExternal22 = 41,
    /// soc_proxy_fatal_alert_external_23
    SocProxyFatalAlertExternal23 = 42,
    /// soc_proxy_recov_alert_external_0
    SocProxyRecovAlertExternal0 = 43,
    /// soc_proxy_recov_alert_external_1
    SocProxyRecovAlertExternal1 = 44,
    /// soc_proxy_recov_alert_external_2
    SocProxyRecovAlertExternal2 = 45,
    /// soc_proxy_recov_alert_external_3
    SocProxyRecovAlertExternal3 = 46,
    /// sram_ctrl_ret_aon_fatal_error
    SramCtrlRetAonFatalError = 47,
    /// rv_dm_fatal_fault
    RvDmFatalFault = 48,
    /// rv_plic_fatal_fault
    RvPlicFatalFault = 49,
    /// aes_recov_ctrl_update_err
    AesRecovCtrlUpdateErr = 50,
    /// aes_fatal_fault
    AesFatalFault = 51,
    /// hmac_fatal_fault
    HmacFatalFault = 52,
    /// kmac_recov_operation_err
    KmacRecovOperationErr = 53,
    /// kmac_fatal_fault_err
    KmacFatalFaultErr = 54,
    /// otbn_fatal
    OtbnFatal = 55,
    /// otbn_recov
    OtbnRecov = 56,
    /// keymgr_dpe_recov_operation_err
    KeymgrDpeRecovOperationErr = 57,
    /// keymgr_dpe_fatal_fault_err
    KeymgrDpeFatalFaultErr = 58,
    /// csrng_recov_alert
    CsrngRecovAlert = 59,
    /// csrng_fatal_alert
    CsrngFatalAlert = 60,
    /// edn0_recov_alert
    Edn0RecovAlert = 61,
    /// edn0_fatal_alert
    Edn0FatalAlert = 62,
    /// edn1_recov_alert
    Edn1RecovAlert = 63,
    /// edn1_fatal_alert
    Edn1FatalAlert = 64,
    /// sram_ctrl_main_fatal_error
    SramCtrlMainFatalError = 65,
    /// sram_ctrl_mbox_fatal_error
    SramCtrlMboxFatalError = 66,
    /// rom_ctrl0_fatal
    RomCtrl0Fatal = 67,
    /// rom_ctrl1_fatal
    RomCtrl1Fatal = 68,
    /// dma_fatal_fault
    DmaFatalFault = 69,
    /// mbx0_fatal_fault
    Mbx0FatalFault = 70,
    /// mbx0_recov_fault
    Mbx0RecovFault = 71,
    /// mbx1_fatal_fault
    Mbx1FatalFault = 72,
    /// mbx1_recov_fault
    Mbx1RecovFault = 73,
    /// mbx2_fatal_fault
    Mbx2FatalFault = 74,
    /// mbx2_recov_fault
    Mbx2RecovFault = 75,
    /// mbx3_fatal_fault
    Mbx3FatalFault = 76,
    /// mbx3_recov_fault
    Mbx3RecovFault = 77,
    /// mbx4_fatal_fault
    Mbx4FatalFault = 78,
    /// mbx4_recov_fault
    Mbx4RecovFault = 79,
    /// mbx5_fatal_fault
    Mbx5FatalFault = 80,
    /// mbx5_recov_fault
    Mbx5RecovFault = 81,
    /// mbx6_fatal_fault
    Mbx6FatalFault = 82,
    /// mbx6_recov_fault
    Mbx6RecovFault = 83,
    /// mbx_jtag_fatal_fault
    MbxJtagFatalFault = 84,
    /// mbx_jtag_recov_fault
    MbxJtagRecovFault = 85,
    /// soc_dbg_ctrl_fatal_fault
    SocDbgCtrlFatalFault = 86,
    /// soc_dbg_ctrl_recov_ctrl_update_err
    SocDbgCtrlRecovCtrlUpdateErr = 87,
    /// racl_ctrl_fatal_fault
    RaclCtrlFatalFault = 88,
    /// racl_ctrl_recov_ctrl_update_err
    RaclCtrlRecovCtrlUpdateErr = 89,
    /// ac_range_check_recov_ctrl_update_err
    AcRangeCheckRecovCtrlUpdateErr = 90,
    /// ac_range_check_fatal_fault
    AcRangeCheckFatalFault = 91,
    /// rv_core_ibex_fatal_sw_err
    RvCoreIbexFatalSwErr = 92,
    /// rv_core_ibex_recov_sw_err
    RvCoreIbexRecovSwErr = 93,
    /// rv_core_ibex_fatal_hw_err
    RvCoreIbexFatalHwErr = 94,
    /// rv_core_ibex_recov_hw_err
    RvCoreIbexRecovHwErr = 95,
}

impl TryFrom<u32> for AlertId {
    type Error = u32;
    fn try_from(val: u32) -> Result<Self, Self::Error> {
        match val {
            0 => Ok(Self::Uart0FatalFault),
            1 => Ok(Self::GpioFatalFault),
            2 => Ok(Self::RvTimerFatalFault),
            3 => Ok(Self::OtpCtrlFatalMacroError),
            4 => Ok(Self::OtpCtrlFatalCheckError),
            5 => Ok(Self::OtpCtrlFatalBusIntegError),
            6 => Ok(Self::OtpCtrlFatalPrimOtpAlert),
            7 => Ok(Self::OtpCtrlRecovPrimOtpAlert),
            8 => Ok(Self::LcCtrlFatalProgError),
            9 => Ok(Self::LcCtrlFatalStateError),
            10 => Ok(Self::LcCtrlFatalBusIntegError),
            11 => Ok(Self::PwrmgrAonFatalFault),
            12 => Ok(Self::RstmgrAonFatalFault),
            13 => Ok(Self::RstmgrAonFatalCnstyFault),
            14 => Ok(Self::ClkmgrAonRecovFault),
            15 => Ok(Self::ClkmgrAonFatalFault),
            16 => Ok(Self::PinmuxAonFatalFault),
            17 => Ok(Self::AonTimerAonFatalFault),
            18 => Ok(Self::SocProxyFatalAlertIntg),
            19 => Ok(Self::SocProxyFatalAlertExternal0),
            20 => Ok(Self::SocProxyFatalAlertExternal1),
            21 => Ok(Self::SocProxyFatalAlertExternal2),
            22 => Ok(Self::SocProxyFatalAlertExternal3),
            23 => Ok(Self::SocProxyFatalAlertExternal4),
            24 => Ok(Self::SocProxyFatalAlertExternal5),
            25 => Ok(Self::SocProxyFatalAlertExternal6),
            26 => Ok(Self::SocProxyFatalAlertExternal7),
            27 => Ok(Self::SocProxyFatalAlertExternal8),
            28 => Ok(Self::SocProxyFatalAlertExternal9),
            29 => Ok(Self::SocProxyFatalAlertExternal10),
            30 => Ok(Self::SocProxyFatalAlertExternal11),
            31 => Ok(Self::SocProxyFatalAlertExternal12),
            32 => Ok(Self::SocProxyFatalAlertExternal13),
            33 => Ok(Self::SocProxyFatalAlertExternal14),
            34 => Ok(Self::SocProxyFatalAlertExternal15),
            35 => Ok(Self::SocProxyFatalAlertExternal16),
            36 => Ok(Self::SocProxyFatalAlertExternal17),
            37 => Ok(Self::SocProxyFatalAlertExternal18),
            38 => Ok(Self::SocProxyFatalAlertExternal19),
            39 => Ok(Self::SocProxyFatalAlertExternal20),
            40 => Ok(Self::SocProxyFatalAlertExternal21),
            41 => Ok(Self::SocProxyFatalAlertExternal22),
            42 => Ok(Self::SocProxyFatalAlertExternal23),
            43 => Ok(Self::SocProxyRecovAlertExternal0),
            44 => Ok(Self::SocProxyRecovAlertExternal1),
            45 => Ok(Self::SocProxyRecovAlertExternal2),
            46 => Ok(Self::SocProxyRecovAlertExternal3),
            47 => Ok(Self::SramCtrlRetAonFatalError),
            48 => Ok(Self::RvDmFatalFault),
            49 => Ok(Self::RvPlicFatalFault),
            50 => Ok(Self::AesRecovCtrlUpdateErr),
            51 => Ok(Self::AesFatalFault),
            52 => Ok(Self::HmacFatalFault),
            53 => Ok(Self::KmacRecovOperationErr),
            54 => Ok(Self::KmacFatalFaultErr),
            55 => Ok(Self::OtbnFatal),
            56 => Ok(Self::OtbnRecov),
            57 => Ok(Self::KeymgrDpeRecovOperationErr),
            58 => Ok(Self::KeymgrDpeFatalFaultErr),
            59 => Ok(Self::CsrngRecovAlert),
            60 => Ok(Self::CsrngFatalAlert),
            61 => Ok(Self::Edn0RecovAlert),
            62 => Ok(Self::Edn0FatalAlert),
            63 => Ok(Self::Edn1RecovAlert),
            64 => Ok(Self::Edn1FatalAlert),
            65 => Ok(Self::SramCtrlMainFatalError),
            66 => Ok(Self::SramCtrlMboxFatalError),
            67 => Ok(Self::RomCtrl0Fatal),
            68 => Ok(Self::RomCtrl1Fatal),
            69 => Ok(Self::DmaFatalFault),
            70 => Ok(Self::Mbx0FatalFault),
            71 => Ok(Self::Mbx0RecovFault),
            72 => Ok(Self::Mbx1FatalFault),
            73 => Ok(Self::Mbx1RecovFault),
            74 => Ok(Self::Mbx2FatalFault),
            75 => Ok(Self::Mbx2RecovFault),
            76 => Ok(Self::Mbx3FatalFault),
            77 => Ok(Self::Mbx3RecovFault),
            78 => Ok(Self::Mbx4FatalFault),
            79 => Ok(Self::Mbx4RecovFault),
            80 => Ok(Self::Mbx5FatalFault),
            81 => Ok(Self::Mbx5RecovFault),
            82 => Ok(Self::Mbx6FatalFault),
            83 => Ok(Self::Mbx6RecovFault),
            84 => Ok(Self::MbxJtagFatalFault),
            85 => Ok(Self::MbxJtagRecovFault),
            86 => Ok(Self::SocDbgCtrlFatalFault),
            87 => Ok(Self::SocDbgCtrlRecovCtrlUpdateErr),
            88 => Ok(Self::RaclCtrlFatalFault),
            89 => Ok(Self::RaclCtrlRecovCtrlUpdateErr),
            90 => Ok(Self::AcRangeCheckRecovCtrlUpdateErr),
            91 => Ok(Self::AcRangeCheckFatalFault),
            92 => Ok(Self::RvCoreIbexFatalSwErr),
            93 => Ok(Self::RvCoreIbexRecovSwErr),
            94 => Ok(Self::RvCoreIbexFatalHwErr),
            95 => Ok(Self::RvCoreIbexRecovHwErr),
            _ => Err(val),
        }
    }
}

/// Alert Handler Alert Source to Peripheral Map
///
/// This array is a mapping from `AlertId` to
/// `AlertPeripheral`.
pub const ALERT_FOR_PERIPHERAL: [AlertPeripheral; 96] = [
    // Uart0FatalFault -> AlertPeripheral::Uart0
    AlertPeripheral::Uart0,
    // GpioFatalFault -> AlertPeripheral::Gpio
    AlertPeripheral::Gpio,
    // RvTimerFatalFault -> AlertPeripheral::RvTimer
    AlertPeripheral::RvTimer,
    // OtpCtrlFatalMacroError -> AlertPeripheral::OtpCtrl
    AlertPeripheral::OtpCtrl,
    // OtpCtrlFatalCheckError -> AlertPeripheral::OtpCtrl
    AlertPeripheral::OtpCtrl,
    // OtpCtrlFatalBusIntegError -> AlertPeripheral::OtpCtrl
    AlertPeripheral::OtpCtrl,
    // OtpCtrlFatalPrimOtpAlert -> AlertPeripheral::OtpCtrl
    AlertPeripheral::OtpCtrl,
    // OtpCtrlRecovPrimOtpAlert -> AlertPeripheral::OtpCtrl
    AlertPeripheral::OtpCtrl,
    // LcCtrlFatalProgError -> AlertPeripheral::LcCtrl
    AlertPeripheral::LcCtrl,
    // LcCtrlFatalStateError -> AlertPeripheral::LcCtrl
    AlertPeripheral::LcCtrl,
    // LcCtrlFatalBusIntegError -> AlertPeripheral::LcCtrl
    AlertPeripheral::LcCtrl,
    // PwrmgrAonFatalFault -> AlertPeripheral::PwrmgrAon
    AlertPeripheral::PwrmgrAon,
    // RstmgrAonFatalFault -> AlertPeripheral::RstmgrAon
    AlertPeripheral::RstmgrAon,
    // RstmgrAonFatalCnstyFault -> AlertPeripheral::RstmgrAon
    AlertPeripheral::RstmgrAon,
    // ClkmgrAonRecovFault -> AlertPeripheral::ClkmgrAon
    AlertPeripheral::ClkmgrAon,
    // ClkmgrAonFatalFault -> AlertPeripheral::ClkmgrAon
    AlertPeripheral::ClkmgrAon,
    // PinmuxAonFatalFault -> AlertPeripheral::PinmuxAon
    AlertPeripheral::PinmuxAon,
    // AonTimerAonFatalFault -> AlertPeripheral::AonTimerAon
    AlertPeripheral::AonTimerAon,
    // SocProxyFatalAlertIntg -> AlertPeripheral::SocProxy
    AlertPeripheral::SocProxy,
    // SocProxyFatalAlertExternal0 -> AlertPeripheral::SocProxy
    AlertPeripheral::SocProxy,
    // SocProxyFatalAlertExternal1 -> AlertPeripheral::SocProxy
    AlertPeripheral::SocProxy,
    // SocProxyFatalAlertExternal2 -> AlertPeripheral::SocProxy
    AlertPeripheral::SocProxy,
    // SocProxyFatalAlertExternal3 -> AlertPeripheral::SocProxy
    AlertPeripheral::SocProxy,
    // SocProxyFatalAlertExternal4 -> AlertPeripheral::SocProxy
    AlertPeripheral::SocProxy,
    // SocProxyFatalAlertExternal5 -> AlertPeripheral::SocProxy
    AlertPeripheral::SocProxy,
    // SocProxyFatalAlertExternal6 -> AlertPeripheral::SocProxy
    AlertPeripheral::SocProxy,
    // SocProxyFatalAlertExternal7 -> AlertPeripheral::SocProxy
    AlertPeripheral::SocProxy,
    // SocProxyFatalAlertExternal8 -> AlertPeripheral::SocProxy
    AlertPeripheral::SocProxy,
    // SocProxyFatalAlertExternal9 -> AlertPeripheral::SocProxy
    AlertPeripheral::SocProxy,
    // SocProxyFatalAlertExternal10 -> AlertPeripheral::SocProxy
    AlertPeripheral::SocProxy,
    // SocProxyFatalAlertExternal11 -> AlertPeripheral::SocProxy
    AlertPeripheral::SocProxy,
    // SocProxyFatalAlertExternal12 -> AlertPeripheral::SocProxy
    AlertPeripheral::SocProxy,
    // SocProxyFatalAlertExternal13 -> AlertPeripheral::SocProxy
    AlertPeripheral::SocProxy,
    // SocProxyFatalAlertExternal14 -> AlertPeripheral::SocProxy
    AlertPeripheral::SocProxy,
    // SocProxyFatalAlertExternal15 -> AlertPeripheral::SocProxy
    AlertPeripheral::SocProxy,
    // SocProxyFatalAlertExternal16 -> AlertPeripheral::SocProxy
    AlertPeripheral::SocProxy,
    // SocProxyFatalAlertExternal17 -> AlertPeripheral::SocProxy
    AlertPeripheral::SocProxy,
    // SocProxyFatalAlertExternal18 -> AlertPeripheral::SocProxy
    AlertPeripheral::SocProxy,
    // SocProxyFatalAlertExternal19 -> AlertPeripheral::SocProxy
    AlertPeripheral::SocProxy,
    // SocProxyFatalAlertExternal20 -> AlertPeripheral::SocProxy
    AlertPeripheral::SocProxy,
    // SocProxyFatalAlertExternal21 -> AlertPeripheral::SocProxy
    AlertPeripheral::SocProxy,
    // SocProxyFatalAlertExternal22 -> AlertPeripheral::SocProxy
    AlertPeripheral::SocProxy,
    // SocProxyFatalAlertExternal23 -> AlertPeripheral::SocProxy
    AlertPeripheral::SocProxy,
    // SocProxyRecovAlertExternal0 -> AlertPeripheral::SocProxy
    AlertPeripheral::SocProxy,
    // SocProxyRecovAlertExternal1 -> AlertPeripheral::SocProxy
    AlertPeripheral::SocProxy,
    // SocProxyRecovAlertExternal2 -> AlertPeripheral::SocProxy
    AlertPeripheral::SocProxy,
    // SocProxyRecovAlertExternal3 -> AlertPeripheral::SocProxy
    AlertPeripheral::SocProxy,
    // SramCtrlRetAonFatalError -> AlertPeripheral::SramCtrlRetAon
    AlertPeripheral::SramCtrlRetAon,
    // RvDmFatalFault -> AlertPeripheral::RvDm
    AlertPeripheral::RvDm,
    // RvPlicFatalFault -> AlertPeripheral::RvPlic
    AlertPeripheral::RvPlic,
    // AesRecovCtrlUpdateErr -> AlertPeripheral::Aes
    AlertPeripheral::Aes,
    // AesFatalFault -> AlertPeripheral::Aes
    AlertPeripheral::Aes,
    // HmacFatalFault -> AlertPeripheral::Hmac
    AlertPeripheral::Hmac,
    // KmacRecovOperationErr -> AlertPeripheral::Kmac
    AlertPeripheral::Kmac,
    // KmacFatalFaultErr -> AlertPeripheral::Kmac
    AlertPeripheral::Kmac,
    // OtbnFatal -> AlertPeripheral::Otbn
    AlertPeripheral::Otbn,
    // OtbnRecov -> AlertPeripheral::Otbn
    AlertPeripheral::Otbn,
    // KeymgrDpeRecovOperationErr -> AlertPeripheral::KeymgrDpe
    AlertPeripheral::KeymgrDpe,
    // KeymgrDpeFatalFaultErr -> AlertPeripheral::KeymgrDpe
    AlertPeripheral::KeymgrDpe,
    // CsrngRecovAlert -> AlertPeripheral::Csrng
    AlertPeripheral::Csrng,
    // CsrngFatalAlert -> AlertPeripheral::Csrng
    AlertPeripheral::Csrng,
    // Edn0RecovAlert -> AlertPeripheral::Edn0
    AlertPeripheral::Edn0,
    // Edn0FatalAlert -> AlertPeripheral::Edn0
    AlertPeripheral::Edn0,
    // Edn1RecovAlert -> AlertPeripheral::Edn1
    AlertPeripheral::Edn1,
    // Edn1FatalAlert -> AlertPeripheral::Edn1
    AlertPeripheral::Edn1,
    // SramCtrlMainFatalError -> AlertPeripheral::SramCtrlMain
    AlertPeripheral::SramCtrlMain,
    // SramCtrlMboxFatalError -> AlertPeripheral::SramCtrlMbox
    AlertPeripheral::SramCtrlMbox,
    // RomCtrl0Fatal -> AlertPeripheral::RomCtrl0
    AlertPeripheral::RomCtrl0,
    // RomCtrl1Fatal -> AlertPeripheral::RomCtrl1
    AlertPeripheral::RomCtrl1,
    // DmaFatalFault -> AlertPeripheral::Dma
    AlertPeripheral::Dma,
    // Mbx0FatalFault -> AlertPeripheral::Mbx0
    AlertPeripheral::Mbx0,
    // Mbx0RecovFault -> AlertPeripheral::Mbx0
    AlertPeripheral::Mbx0,
    // Mbx1FatalFault -> AlertPeripheral::Mbx1
    AlertPeripheral::Mbx1,
    // Mbx1RecovFault -> AlertPeripheral::Mbx1
    AlertPeripheral::Mbx1,
    // Mbx2FatalFault -> AlertPeripheral::Mbx2
    AlertPeripheral::Mbx2,
    // Mbx2RecovFault -> AlertPeripheral::Mbx2
    AlertPeripheral::Mbx2,
    // Mbx3FatalFault -> AlertPeripheral::Mbx3
    AlertPeripheral::Mbx3,
    // Mbx3RecovFault -> AlertPeripheral::Mbx3
    AlertPeripheral::Mbx3,
    // Mbx4FatalFault -> AlertPeripheral::Mbx4
    AlertPeripheral::Mbx4,
    // Mbx4RecovFault -> AlertPeripheral::Mbx4
    AlertPeripheral::Mbx4,
    // Mbx5FatalFault -> AlertPeripheral::Mbx5
    AlertPeripheral::Mbx5,
    // Mbx5RecovFault -> AlertPeripheral::Mbx5
    AlertPeripheral::Mbx5,
    // Mbx6FatalFault -> AlertPeripheral::Mbx6
    AlertPeripheral::Mbx6,
    // Mbx6RecovFault -> AlertPeripheral::Mbx6
    AlertPeripheral::Mbx6,
    // MbxJtagFatalFault -> AlertPeripheral::MbxJtag
    AlertPeripheral::MbxJtag,
    // MbxJtagRecovFault -> AlertPeripheral::MbxJtag
    AlertPeripheral::MbxJtag,
    // SocDbgCtrlFatalFault -> AlertPeripheral::SocDbgCtrl
    AlertPeripheral::SocDbgCtrl,
    // SocDbgCtrlRecovCtrlUpdateErr -> AlertPeripheral::SocDbgCtrl
    AlertPeripheral::SocDbgCtrl,
    // RaclCtrlFatalFault -> AlertPeripheral::RaclCtrl
    AlertPeripheral::RaclCtrl,
    // RaclCtrlRecovCtrlUpdateErr -> AlertPeripheral::RaclCtrl
    AlertPeripheral::RaclCtrl,
    // AcRangeCheckRecovCtrlUpdateErr -> AlertPeripheral::AcRangeCheck
    AlertPeripheral::AcRangeCheck,
    // AcRangeCheckFatalFault -> AlertPeripheral::AcRangeCheck
    AlertPeripheral::AcRangeCheck,
    // RvCoreIbexFatalSwErr -> AlertPeripheral::RvCoreIbex
    AlertPeripheral::RvCoreIbex,
    // RvCoreIbexRecovSwErr -> AlertPeripheral::RvCoreIbex
    AlertPeripheral::RvCoreIbex,
    // RvCoreIbexFatalHwErr -> AlertPeripheral::RvCoreIbex
    AlertPeripheral::RvCoreIbex,
    // RvCoreIbexRecovHwErr -> AlertPeripheral::RvCoreIbex
    AlertPeripheral::RvCoreIbex,
];

// PERIPH_INSEL ranges from 0 to NUM_MIO_PADS + 2 -1}
//  0 and 1 are tied to value 0 and 1
pub const NUM_MIO_PADS: usize = 12;
pub const NUM_DIO_PADS: usize = 58;

pub const PINMUX_MIO_PERIPH_INSEL_IDX_OFFSET: usize = 2;
pub const PINMUX_PERIPH_OUTSEL_IDX_OFFSET: usize = 3;

/// Pinmux Peripheral Input.
#[derive(Copy, Clone, PartialEq, Eq)]
#[repr(u32)]
pub enum PinmuxPeripheralIn {
    /// Peripheral Input 0
    SocProxySocGpi12 = 0,
    /// Peripheral Input 1
    SocProxySocGpi13 = 1,
    /// Peripheral Input 2
    SocProxySocGpi14 = 2,
    /// Peripheral Input 3
    SocProxySocGpi15 = 3,
}

impl TryFrom<u32> for PinmuxPeripheralIn {
    type Error = u32;
    fn try_from(val: u32) -> Result<Self, Self::Error> {
        match val {
            0 => Ok(Self::SocProxySocGpi12),
            1 => Ok(Self::SocProxySocGpi13),
            2 => Ok(Self::SocProxySocGpi14),
            3 => Ok(Self::SocProxySocGpi15),
            _ => Err(val),
        }
    }
}

/// Pinmux MIO Input Selector.
#[derive(Copy, Clone, PartialEq, Eq)]
#[repr(u32)]
pub enum PinmuxInsel {
    /// Tie constantly to zero
    ConstantZero = 0,
    /// Tie constantly to one
    ConstantOne = 1,
    /// MIO Pad 0
    Mio0 = 2,
    /// MIO Pad 1
    Mio1 = 3,
    /// MIO Pad 2
    Mio2 = 4,
    /// MIO Pad 3
    Mio3 = 5,
    /// MIO Pad 4
    Mio4 = 6,
    /// MIO Pad 5
    Mio5 = 7,
    /// MIO Pad 6
    Mio6 = 8,
    /// MIO Pad 7
    Mio7 = 9,
    /// MIO Pad 8
    Mio8 = 10,
    /// MIO Pad 9
    Mio9 = 11,
    /// MIO Pad 10
    Mio10 = 12,
    /// MIO Pad 11
    Mio11 = 13,
}

impl TryFrom<u32> for PinmuxInsel {
    type Error = u32;
    fn try_from(val: u32) -> Result<Self, Self::Error> {
        match val {
            0 => Ok(Self::ConstantZero),
            1 => Ok(Self::ConstantOne),
            2 => Ok(Self::Mio0),
            3 => Ok(Self::Mio1),
            4 => Ok(Self::Mio2),
            5 => Ok(Self::Mio3),
            6 => Ok(Self::Mio4),
            7 => Ok(Self::Mio5),
            8 => Ok(Self::Mio6),
            9 => Ok(Self::Mio7),
            10 => Ok(Self::Mio8),
            11 => Ok(Self::Mio9),
            12 => Ok(Self::Mio10),
            13 => Ok(Self::Mio11),
            _ => Err(val),
        }
    }
}

/// Pinmux MIO Output.
#[derive(Copy, Clone, PartialEq, Eq)]
#[repr(u32)]
pub enum PinmuxMioOut {
    /// MIO Pad 0
    Mio0 = 0,
    /// MIO Pad 1
    Mio1 = 1,
    /// MIO Pad 2
    Mio2 = 2,
    /// MIO Pad 3
    Mio3 = 3,
    /// MIO Pad 4
    Mio4 = 4,
    /// MIO Pad 5
    Mio5 = 5,
    /// MIO Pad 6
    Mio6 = 6,
    /// MIO Pad 7
    Mio7 = 7,
    /// MIO Pad 8
    Mio8 = 8,
    /// MIO Pad 9
    Mio9 = 9,
    /// MIO Pad 10
    Mio10 = 10,
    /// MIO Pad 11
    Mio11 = 11,
}

impl TryFrom<u32> for PinmuxMioOut {
    type Error = u32;
    fn try_from(val: u32) -> Result<Self, Self::Error> {
        match val {
            0 => Ok(Self::Mio0),
            1 => Ok(Self::Mio1),
            2 => Ok(Self::Mio2),
            3 => Ok(Self::Mio3),
            4 => Ok(Self::Mio4),
            5 => Ok(Self::Mio5),
            6 => Ok(Self::Mio6),
            7 => Ok(Self::Mio7),
            8 => Ok(Self::Mio8),
            9 => Ok(Self::Mio9),
            10 => Ok(Self::Mio10),
            11 => Ok(Self::Mio11),
            _ => Err(val),
        }
    }
}

/// Pinmux Peripheral Output Selector.
#[derive(Copy, Clone, PartialEq, Eq)]
#[repr(u32)]
pub enum PinmuxOutsel {
    /// Tie constantly to zero
    ConstantZero = 0,
    /// Tie constantly to one
    ConstantOne = 1,
    /// Tie constantly to high-Z
    ConstantHighZ = 2,
    /// Peripheral Output 0
    SocProxySocGpo12 = 3,
    /// Peripheral Output 1
    SocProxySocGpo13 = 4,
    /// Peripheral Output 2
    SocProxySocGpo14 = 5,
    /// Peripheral Output 3
    SocProxySocGpo15 = 6,
    /// Peripheral Output 4
    OtpMacroTest0 = 7,
}

impl TryFrom<u32> for PinmuxOutsel {
    type Error = u32;
    fn try_from(val: u32) -> Result<Self, Self::Error> {
        match val {
            0 => Ok(Self::ConstantZero),
            1 => Ok(Self::ConstantOne),
            2 => Ok(Self::ConstantHighZ),
            3 => Ok(Self::SocProxySocGpo12),
            4 => Ok(Self::SocProxySocGpo13),
            5 => Ok(Self::SocProxySocGpo14),
            6 => Ok(Self::SocProxySocGpo15),
            7 => Ok(Self::OtpMacroTest0),
            _ => Err(val),
        }
    }
}

/// Dedicated Pad Selects
#[derive(Copy, Clone, PartialEq, Eq)]
#[repr(u32)]
pub enum DirectPads {
    GpioGpio0 = 0,
    GpioGpio1 = 1,
    GpioGpio2 = 2,
    GpioGpio3 = 3,
    GpioGpio4 = 4,
    GpioGpio5 = 5,
    GpioGpio6 = 6,
    GpioGpio7 = 7,
    GpioGpio8 = 8,
    GpioGpio9 = 9,
    GpioGpio10 = 10,
    GpioGpio11 = 11,
    GpioGpio12 = 12,
    GpioGpio13 = 13,
    GpioGpio14 = 14,
    GpioGpio15 = 15,
    GpioGpio16 = 16,
    GpioGpio17 = 17,
    GpioGpio18 = 18,
    GpioGpio19 = 19,
    GpioGpio20 = 20,
    GpioGpio21 = 21,
    GpioGpio22 = 22,
    GpioGpio23 = 23,
    GpioGpio24 = 24,
    GpioGpio25 = 25,
    GpioGpio26 = 26,
    GpioGpio27 = 27,
    GpioGpio28 = 28,
    GpioGpio29 = 29,
    GpioGpio30 = 30,
    GpioGpio31 = 31,
    Uart0Rx = 32,
    SocProxySocGpi0 = 33,
    SocProxySocGpi1 = 34,
    SocProxySocGpi2 = 35,
    SocProxySocGpi3 = 36,
    SocProxySocGpi4 = 37,
    SocProxySocGpi5 = 38,
    SocProxySocGpi6 = 39,
    SocProxySocGpi7 = 40,
    SocProxySocGpi8 = 41,
    SocProxySocGpi9 = 42,
    SocProxySocGpi10 = 43,
    SocProxySocGpi11 = 44,
    Uart0Tx = 45,
    SocProxySocGpo0 = 46,
    SocProxySocGpo1 = 47,
    SocProxySocGpo2 = 48,
    SocProxySocGpo3 = 49,
    SocProxySocGpo4 = 50,
    SocProxySocGpo5 = 51,
    SocProxySocGpo6 = 52,
    SocProxySocGpo7 = 53,
    SocProxySocGpo8 = 54,
    SocProxySocGpo9 = 55,
    SocProxySocGpo10 = 56,
    SocProxySocGpo11 = 57,
}

impl TryFrom<u32> for DirectPads {
    type Error = u32;
    fn try_from(val: u32) -> Result<Self, Self::Error> {
        match val {
            0 => Ok(Self::GpioGpio0),
            1 => Ok(Self::GpioGpio1),
            2 => Ok(Self::GpioGpio2),
            3 => Ok(Self::GpioGpio3),
            4 => Ok(Self::GpioGpio4),
            5 => Ok(Self::GpioGpio5),
            6 => Ok(Self::GpioGpio6),
            7 => Ok(Self::GpioGpio7),
            8 => Ok(Self::GpioGpio8),
            9 => Ok(Self::GpioGpio9),
            10 => Ok(Self::GpioGpio10),
            11 => Ok(Self::GpioGpio11),
            12 => Ok(Self::GpioGpio12),
            13 => Ok(Self::GpioGpio13),
            14 => Ok(Self::GpioGpio14),
            15 => Ok(Self::GpioGpio15),
            16 => Ok(Self::GpioGpio16),
            17 => Ok(Self::GpioGpio17),
            18 => Ok(Self::GpioGpio18),
            19 => Ok(Self::GpioGpio19),
            20 => Ok(Self::GpioGpio20),
            21 => Ok(Self::GpioGpio21),
            22 => Ok(Self::GpioGpio22),
            23 => Ok(Self::GpioGpio23),
            24 => Ok(Self::GpioGpio24),
            25 => Ok(Self::GpioGpio25),
            26 => Ok(Self::GpioGpio26),
            27 => Ok(Self::GpioGpio27),
            28 => Ok(Self::GpioGpio28),
            29 => Ok(Self::GpioGpio29),
            30 => Ok(Self::GpioGpio30),
            31 => Ok(Self::GpioGpio31),
            32 => Ok(Self::Uart0Rx),
            33 => Ok(Self::SocProxySocGpi0),
            34 => Ok(Self::SocProxySocGpi1),
            35 => Ok(Self::SocProxySocGpi2),
            36 => Ok(Self::SocProxySocGpi3),
            37 => Ok(Self::SocProxySocGpi4),
            38 => Ok(Self::SocProxySocGpi5),
            39 => Ok(Self::SocProxySocGpi6),
            40 => Ok(Self::SocProxySocGpi7),
            41 => Ok(Self::SocProxySocGpi8),
            42 => Ok(Self::SocProxySocGpi9),
            43 => Ok(Self::SocProxySocGpi10),
            44 => Ok(Self::SocProxySocGpi11),
            45 => Ok(Self::Uart0Tx),
            46 => Ok(Self::SocProxySocGpo0),
            47 => Ok(Self::SocProxySocGpo1),
            48 => Ok(Self::SocProxySocGpo2),
            49 => Ok(Self::SocProxySocGpo3),
            50 => Ok(Self::SocProxySocGpo4),
            51 => Ok(Self::SocProxySocGpo5),
            52 => Ok(Self::SocProxySocGpo6),
            53 => Ok(Self::SocProxySocGpo7),
            54 => Ok(Self::SocProxySocGpo8),
            55 => Ok(Self::SocProxySocGpo9),
            56 => Ok(Self::SocProxySocGpo10),
            57 => Ok(Self::SocProxySocGpo11),
            _ => Err(val),
        }
    }
}

/// Muxed Pad Selects
#[derive(Copy, Clone, PartialEq, Eq)]
#[repr(u32)]
pub enum MuxedPads {
    Mio0 = 0,
    Mio1 = 1,
    Mio2 = 2,
    Mio3 = 3,
    Mio4 = 4,
    Mio5 = 5,
    Mio6 = 6,
    Mio7 = 7,
    Mio8 = 8,
    Mio9 = 9,
    Mio10 = 10,
    Mio11 = 11,
}

impl TryFrom<u32> for MuxedPads {
    type Error = u32;
    fn try_from(val: u32) -> Result<Self, Self::Error> {
        match val {
            0 => Ok(Self::Mio0),
            1 => Ok(Self::Mio1),
            2 => Ok(Self::Mio2),
            3 => Ok(Self::Mio3),
            4 => Ok(Self::Mio4),
            5 => Ok(Self::Mio5),
            6 => Ok(Self::Mio6),
            7 => Ok(Self::Mio7),
            8 => Ok(Self::Mio8),
            9 => Ok(Self::Mio9),
            10 => Ok(Self::Mio10),
            11 => Ok(Self::Mio11),
            _ => Err(val),
        }
    }
}

/// Power Manager Wakeup Signals
#[derive(Copy, Clone, PartialEq, Eq)]
#[repr(u32)]
pub enum PowerManagerWakeUps {
    PinmuxAonPinWkupReq = 0,
    AonTimerAonWkupReq = 1,
    SocProxyWkupInternalReq = 2,
    SocProxyWkupExternalReq = 3,
}

/// Reset Manager Software Controlled Resets
#[derive(Copy, Clone, PartialEq, Eq)]
#[repr(u32)]
pub enum ResetManagerSwResets {
    SysSrc = 0,
}

/// Power Manager Reset Request Signals
#[derive(Copy, Clone, PartialEq, Eq)]
#[repr(u32)]
pub enum PowerManagerResetRequests {
    AonTimerAonAonTimerRstReq = 0,
    SocProxyRstReqExternal = 1,
}

/// Clock Manager Software-Controlled ("Gated") Clocks.
///
/// The Software has full control over these clocks.
#[derive(Copy, Clone, PartialEq, Eq)]
#[repr(u32)]
pub enum GateableClocks {
    /// Clock clk_io_div4_peri in group peri
    IoDiv4Peri = 0,
}

/// Clock Manager Software-Hinted Clocks.
///
/// The Software has partial control over these clocks. It can ask them to stop,
/// but the clock manager is in control of whether the clock actually is stopped.
#[derive(Copy, Clone, PartialEq, Eq)]
#[repr(u32)]
pub enum HintableClocks {
    /// Clock clk_main_aes in group trans
    MainAes = 0,
    /// Clock clk_main_hmac in group trans
    MainHmac = 1,
    /// Clock clk_main_kmac in group trans
    MainKmac = 2,
    /// Clock clk_main_otbn in group trans
    MainOtbn = 3,
}

/// MMIO Region
///
/// MMIO region excludes any memory that is separate from the module
/// configuration space, i.e. ROM, main SRAM, and mbx SRAM are excluded but
/// retention SRAM or spi_device are included.
pub const TOP_DARIC2_MMIO_BASE_ADDR: usize = 0x21100000;
pub const TOP_DARIC2_MMIO_SIZE_BYTES: usize = 0xF501000;
