// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0

#ifndef OPENTITAN_SW_DEVICE_TESTS_ACC_RANDOMNESS_IMPL_H_
#define OPENTITAN_SW_DEVICE_TESTS_ACC_RANDOMNESS_IMPL_H_

#include <stdbool.h>

#include "sw/device/lib/dif/dif_acc.h"

/**
 * Prepares the ACC randomness test.
 *
 * Does the same as acc_randomness_test_start() without
 * executing the test.
 *
 * @param acc A ACC dif handle.
 * @param iters The number of entropy requests to the RND CSR.
 */
void acc_randomness_test_prepare(dif_acc_t *acc, uint32_t iters);

/**
 * Starts ACC randomness test.
 *
 * Requires EDN0 and EDN1 to be serving entropy, as well as an initialized
 * `acc` runtime handle. A Randomness test is loaded into ACC. Use the
 * `acc_randomness_test_end()` function to check the test status. This function
 * is non-blocking.
 *
 * @param acc A ACC dif handle.
 * @param iters The number of entropy requests to the RND CSR.
 */
void acc_randomness_test_start(dif_acc_t *acc, uint32_t iters);

/**
 * Checks the ACC randomness test result.
 *
 * This function must be called after `acc_randomness_test_start()`.
 *
 * @param acc A ACC dif handle.
 * @param skip_acc_done_check Set to true to skip ACC done execution check.
 * The check is blocking.
 * @returns true on test pass, false otherwise.
 */
bool acc_randomness_test_end(dif_acc_t *acc, bool skip_acc_done_check);

/**
 * Prints the randomness data generated by the test.
 *
 * This function must be called after ACC is done executing the program loaded
 * by the `acc_randomness_test_start()` function.
 *
 * @param acc A ACC dif handle.
 */
void acc_randomness_test_log_results(dif_acc_t *acc);

#endif  // OPENTITAN_SW_DEVICE_TESTS_ACC_RANDOMNESS_IMPL_H_
