// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0

#include "sw/device/tests/acc_randomness_impl.h"

#include "sw/device/lib/dif/dif_base.h"
#include "sw/device/lib/dif/dif_acc.h"
#include "sw/device/lib/runtime/log.h"
#include "sw/device/lib/testing/acc_testutils.h"
#include "sw/device/lib/testing/test_framework/check.h"

ACC_DECLARE_APP_SYMBOLS(randomness);
ACC_DECLARE_SYMBOL_ADDR(randomness, iterations);
ACC_DECLARE_SYMBOL_ADDR(randomness, rv);
ACC_DECLARE_SYMBOL_ADDR(randomness, fail_idx);
ACC_DECLARE_SYMBOL_ADDR(randomness, rnd_out);
ACC_DECLARE_SYMBOL_ADDR(randomness, urnd_out);

static const acc_app_t kAccAppRandomnessApp = ACC_APP_T_INIT(randomness);
static const acc_addr_t kVarIters = ACC_ADDR_T_INIT(randomness, iterations);
static const acc_addr_t kVarRv = ACC_ADDR_T_INIT(randomness, rv);
static const acc_addr_t kVarFailIdx = ACC_ADDR_T_INIT(randomness, fail_idx);
static const acc_addr_t kVarRndOut = ACC_ADDR_T_INIT(randomness, rnd_out);
static const acc_addr_t kVarUrndOut = ACC_ADDR_T_INIT(randomness, urnd_out);

/**
 * LOG_INFO with a 256b unsigned integer as hexadecimal number with a prefix.
 */
static void print_uint256(dif_acc_t *acc, const acc_addr_t var,
                          const char *prefix) {
  uint32_t data[32 / sizeof(uint32_t)];
  CHECK_STATUS_OK(acc_testutils_read_data(acc, /*len_bytes=*/32, var, &data));
  LOG_INFO("%s0x%08x%08x%08x%08x%08x%08x%08x%08x", prefix, data[7], data[6],
           data[5], data[4], data[3], data[2], data[1], data[0]);
}

void acc_randomness_test_start(dif_acc_t *acc, uint32_t iters) {
  acc_randomness_test_prepare(acc, iters);
  CHECK_STATUS_OK(acc_testutils_execute(acc));
}

void acc_randomness_test_prepare(dif_acc_t *acc, uint32_t iters) {
  // Reset the `kVarRv` value to ensure the result loaded by
  // `acc_randomness_test_end()` is the one generated by ACC.
  uint32_t rv = UINT32_MAX;
  CHECK_STATUS_OK(
      acc_testutils_write_data(acc, sizeof(uint32_t), &rv, kVarRv));
  CHECK_STATUS_OK(acc_testutils_load_app(acc, kAccAppRandomnessApp));
  CHECK_STATUS_OK(
      acc_testutils_write_data(acc, sizeof(uint32_t), &iters, kVarIters));
}

bool acc_randomness_test_end(dif_acc_t *acc, bool skip_acc_done_check) {
  if (!skip_acc_done_check) {
    CHECK_STATUS_OK(acc_testutils_wait_for_done(acc, kDifAccErrBitsNoError));
  }
  uint32_t rv;
  CHECK_STATUS_OK(acc_testutils_read_data(acc, /*len_bytes=*/4, kVarRv, &rv));
  if (rv != 0) {
    uint32_t fail_idx;
    CHECK_STATUS_OK(acc_testutils_read_data(acc, /*len_bytes=*/4, kVarFailIdx,
                                             &fail_idx));
    LOG_ERROR("ERROR: Test with index %d failed.", fail_idx);
    return false;
  }
  return true;
}

void acc_randomness_test_log_results(dif_acc_t *acc) {
  print_uint256(acc, kVarRndOut, "rnd = ");
  print_uint256(acc, kVarUrndOut, "urnd = ");
}
