# Copyright lowRISC contributors (OpenTitan project).
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

load("//rules:acc.bzl", "acc_binary")

package(default_visibility = ["//visibility:public"])

acc_binary(
    name = "acc_insn_carry_flag",
    srcs = [
        "acc_insn_carry_flag.s",
    ],
)

acc_binary(
    name = "acc_key_sideload_sca",
    srcs = [
        "acc_key_sideload_sca.s",
    ],
)

acc_binary(
    name = "acc_insn_combi_ops",
    srcs = [
        "acc_insn_combi_ops.s",
    ],
)
