# Copyright lowRISC contributors (OpenTitan project).
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

load("//rules:acc.bzl", "acc_binary")

package(default_visibility = ["//visibility:public"])

acc_binary(
    name = "barrett384",
    srcs = [
        "barrett384.s",
    ],
)

acc_binary(
    name = "err_test",
    srcs = [
        "err_test.s",
    ],
)

acc_binary(
    name = "loop",
    srcs = [
        "loop.s",
    ],
)

acc_binary(
    name = "mul256",
    srcs = [
        "mul256.s",
    ],
)

acc_binary(
    name = "mul384",
    srcs = [
        "mul384.s",
    ],
)

acc_binary(
    name = "pseudo-ops",
    srcs = [
        "pseudo-ops.s",
    ],
)

acc_binary(
    name = "solinas384",
    srcs = [
        "solinas384.s",
    ],
)

acc_binary(
    name = "randomness",
    srcs = [
        "randomness.s",
    ],
)

acc_binary(
    name = "calc_montgomery_consts",
    srcs = [
        "calc_montgomery_consts.s",
    ],
)
