# Copyright lowRISC contributors (OpenTitan project).
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

load("//hw/top:defs.bzl", "opentitan_require_top")
load("@rules_rust//rust:defs.bzl", "rust_binary")

package(default_visibility = ["//visibility:public"])

rust_binary(
    name = "manuf_cp_yield_test",
    srcs = [
        "src/main.rs",
    ],
    # TODO: Darjeeling support
    target_compatible_with = opentitan_require_top("earlgrey"),
    deps = [
        "//sw/host/opentitanlib",
        "//sw/host/ot_hal",
        "@crate_index//:anyhow",
        "@crate_index//:clap",
        "@crate_index//:log",
    ],
)
