# Copyright lowRISC contributors (OpenTitan project).
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

name: CI
on:
  pull_request:
  push:
    branches-ignore:
      - "backport-*"
    tags:
      - "*"

permissions:
  contents: read
  # Needed for workload identity federation
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

env:
  VIVADO_VERSION: "2021.1"
  # Release tag from https://github.com/lowRISC/lowrisc-toolchains/releases
  TOOLCHAIN_VERSION: 20220210-1

jobs:
  quick_lint:
    name: Lint (quick)
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required so we can lint commit messages.
      - name: Prepare environment
        uses: ./.github/actions/prepare-env
        with:
          service_account_json: '${{ secrets.BAZEL_CACHE_CREDS }}'
      - name: Show environment
        run: ./ci/scripts/show-env.sh

  verilator_earlgrey:
    name: Verilated Earl Grey
    runs-on: ubuntu-20.04
    needs: quick_lint
    timeout-minutes: 240
    steps:
      - uses: actions/checkout@v4
      - name: Prepare environment
        uses: ./.github/actions/prepare-env
        with:
          service_account_json: '${{ secrets.BAZEL_CACHE_CREDS }}'
      - name: Run fast Verilator tests
        run: ./ci/scripts/run-verilator-tests.sh
      - name: Publish Bazel test results
        uses: ./.github/actions/publish-bazel-test-results
        if: ${{ !cancelled() }}
        with:
          artifact-name: verilator_earlgrey-test-results
      - name: Upload Bazel execution logs
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: exec_log.1.log
          path: build.log

  verilator_earlgrey_dup:
    name: Verilated Earl Grey (Duplicated)
    runs-on: ubuntu-20.04
    needs: quick_lint
    timeout-minutes: 240
    steps:
      - uses: actions/checkout@v4
      - name: Prepare environment
        uses: ./.github/actions/prepare-env
        with:
          service_account_json: '${{ secrets.BAZEL_CACHE_CREDS }}'
      - name: Run fast Verilator tests
        run: ./ci/scripts/run-verilator-tests.sh
      - name: Publish Bazel test results
        uses: ./.github/actions/publish-bazel-test-results
        if: ${{ !cancelled() }}
        with:
          artifact-name: verilator_earlgrey-test-results
      - name: Upload Bazel execution logs
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: exec_log.2.log
          path: build.log